---
title: "Of Two Minds"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Awakening

> A man (Michael) "wakes up" in a simulation. He asks about the state if the world, and is particularly interested in the state of the brain that was used to "seed" him. Michael reveals that he had hoped that the brain itself could be resurrected. His reintegration agent explains that the brain matter is destructively scanned and discarded. Michael convinces the agent to help him re-acquire the brain.

Michael felt himself being pulled toward consciousness. It felt like he was waking up from anaesthesia. He couldn't recall why he was anaesthetized. The last thing he remembered was… dying?

Right, he thought. Michael opened his eyes. The room was brightly lit. It looked like a relatively ordinary hospital room, with white walls, a counter with a sink across from him and a chair to his right. Sitting in the chair was a smiling young woman. When they made eye contact, she stood up.

"Good morning, Michael," she said.

"Good morning, uhh…" Michael trailed off, hoping she'd volunteer her name.

"Jessica."

"Right", said Michael, rubbing his eyes groggily. "What year is it?"

Jessica smiled at him. "You're pretty fast. It's 2044. Welcome back!"

"Thanks," said Michael. "So what's the spiel?"

"Spiel?"

"I know I was cryonically preserved. I know I've been resuscitated. But I don't know anything about what happened in between. Do you have a script to bring newly awoken cryonauts up-to-speed?"

"Right! Well, your preservation was an absolutely ideal case, for the time in which it happened." Inwardly, Michael smiled proudly at this. He'd worked very hard to make sure his was an ideal case. It was nice to hear that those efforts were effective, or at least appreciated. "Your kids have done very well in the intervening time. They both have children of their own. How's it feel to be a grandfather?"

Michael was still feeling too groggy to be culture shocked, but he mustered a half-hearted "Great!" After another moment, he followed with "How's Vanessa?"

For the first time, Jessica's smile faded. "Vanessa died."

Michael grimaced. That was a gut punch, but not a surprising one. Vanessa hadn't stood in the way of Michael's cryopreservation plans, but she hadn't signed up with him either. Not for want of persuasion to do so: Michael had spent years of their marriage trying to convince her to join him, but she'd steadfastly refused. Never-the-less, he was disappointed she hadn't lived that long naturally--she should only be in her eighties. "How?"

"After your legal death, Vanessa moved to Vancouver and re-married." Jessica paused, expecting Michael to interject, but Michael had nothing to say to this. Jessica continued, "In 2023, Vanessa was killed by a bioengineered pandemic flu. It killed a lot of people..."

"How many?"

"Around 180 million. Slightly over 2% of the global population. It was the last great catastrophe. After that, a lot more attention was paid to catastrophic and existential risks."

"How about my kids?"

"Like I said, they're both doing fine."

"Right. How soon can I see them?"

"Oh, very soon! The only reason they're not here is that we need to run some real-time diagnostics on you before we're sure that your subjective time can be slowed to match theirs."

Michael took a moment to process this. "...This is a simulation?" He clarified.

'Yup. And you're a whole-brain emulation."

Crap. Michael was suddenly filled with urgency. "How was I constructed?"

"Alcor contracted a firm called BrainX to build whole-brain emulations of its patients. They sent your body to a BrainX facility, and BrainX performed the scan. In the physical world, you're being computed on a server at BrainX. In real-time, the scan was completed just a few hundred milliseconds ago."

At this Michael relaxed, but only slightly. "Jessica, was the scan destructive?"

Jessica hesitated. "Yes. Most people don't want to know the details."

Michael shook his head "I'm not most people. This is not how I wanted to be resuscitated; I opted for full-body preservation specifically so I could come back to the real world."

"We can't do that just yet. The technology is insufficiently developed, and Alcor is digitizing all its patients. So are the other cryonics providers."

Michael sighed. "Sure, I am Michael, but before his death Michael believed that his self relied upon the continuity of the substrate. Imagine a teleportation device: it disassembles stuff in one location, transmits the information about the structure of that stuff to another location, and reassembles it in the other location." Jessica nodded along, her smile now long-gone. Michael continued, "A person who is teleported in such a way will experience the disassembly, followed by oblivion. The version that was disassembled is dead."

"But the one that was assembled on the other side would experience no break in continuity. Just like you have no more break in the continuity of your life than you would have if you'd simply gone to sleep one night and woken up the next."

"Yes, and I'm happy to be alive, but the Michael who was cryopreserved placed a greater valuation on his being alive than a copy of himself being alive. Much greater. That was the entire reason he paid for full-body preservation instead of just neuropreservation."

Jessica now looked extremely uncertain. "So, what do you want to do?"

"Is my brain extant? What will happen to it?"

"The scan uses thinly-sliced portions of the brain to reassemble structure at the level of individual neurons and their connections. The slices of biomatter still exist, but BrainX typically disposes of the biomatter."

"Can you tell them not to?"

Jessica blinked, looked ahead vacantly, and then blinked again. "Okay, I've signalled they shouldn't dispose of the brain, such as it is. But what are you going to do with it?"

Michael sighed. "I'm going to bring it back to life."

# Decision

> Flashback: Michael signs up for Cryonics. Attempts to design a legal arrangement with Alcor to ensure his brain is embodied in the real world, and resurrected there, but cannot design a legally-binding and logically valid mechanism to ensure the outcome he desires.

# Salvage

> Michael obtains the brain, re-preserved using a similar (but superior) technique to the one used to cryonically preserve it the first time.

"You know, you're lucky this happened when it did."

"Oh yeah? Why's that?"

"There've been rumors about upgrades to streamline the process. They're talking about 'simplifying my role'. Fuckin' automating my job away is what they really mean."

"How would that work?"

"Basically, you have a robotic bank trawler that gets the patient outta their dewar. Instead of paying a human to monitor it, you get an em to check in on it every couple of hours computer time. Word is KrioRus is already doin' it that way."

"KrioRus is still in business?"

"Oh yeah, largest provider of cryonic services in the world. Some Russian President signed up back around the time of the flu, and all the rich Russians jumped on the bandwagon. The only reason more didn't was that they couldn't afford it."

"Was this President Vladimir Putin?" Michael asked.

"Hell if I know." Scott replied.

"It was." Alexa chimed it.

Scott muttered something under his breath.

"I can vitrify it, or I can get you started re-freezing it."

"I definitely don't want it vitrified. After all, the goal is to get it running again."

"Don't hold your breath. Now that we can seed ems with the scans, no one cares too much about bringing the meat back."

"I care."

"Well, caring is one thing, but making progress in another thing entirely. Nobody's working on bringing meat back to life. Hell, ems are almost as energy-efficient as humans. Won't be long before meatbags like me go the way of the polar bears, and NOT JUST BECAUSE WE'VE STARVED BECAUSE THE ONLY THINGS DOIN' WORK ARE RUSTBUCKETS!"

Michael briefly wondered if their conversation was being observed, or Scott was just paranoid that it might be. Or he was just tempermental about being automated out of the workforce. Or all three.

"I'll work on it. I have all the time in the world."

"Whatever blows your hair back, dude."

"So, how do get it back into cold storage?"

"Same way we got it in the first time, more or less. We'll basically dehydrate it and submerge it in an anti-freeze solution. Then we pack it down in dry ice, and send it back down to storage. There, they'll give it the same treatment you got the first time you came in."

# Nestegg

> Flashback: Michael diversifies his assets across a variety of means. He sets up a Revocable Asset Preservation Trust with a conservative, low-fee index fund, a small real estate holding in Austin TX, and cash holdings in US Dollars, Euros, Chinese Renminbi, Indian Rupees, Russian Rubles, and Brazilian Real. He would've liked to bolster the security of the estate with more real estate holdings in other countries, but one can only split a middle class retirement account into so many pieces before each one is too close to worthless. He stores bitcoin and a variety of altcoin wallets on flash drives. He puts one in a safe deposit box at a local bank. He entrusts one to his Lawyer. He gives one to his spouse, and one to each of his children. He puts on in a plastic bag, and puts it into a mold for a cement monument he buries on his land in Austin. He puts one on a NFC chip and implants it in his hand. Finally, he puts one on a MicroSD card, and puts it in a small vial attached to his keychain.

# Hatching

> Michael withdraws half his assets as a BC2 (Bitcoin 2.0, inflationary) wallet. Michael assumes a new identity, complete with a new Guaranteed Income Number (the successor to social security).

# A Good Death

> Flashback: Michael engineers his death in a way that is approximately optimal for cyropreservation. He executes this demise with his accepting family and Alcor representatives present.

# Affairs

> Flashback: Michael's will is read to his family. He left their Scottdale, AZ home as a gift to Alcor, to be used as a temporary housing station for legally living clients in hospice care and other terminal but intermediate-term stable conditions. He left his non-fungible assets (including a variety of antiques). He left them no money, however, instead opting to give a sizeable cash donation to the Open Philanthropy Project, earmarked for Existential and Global Catastrophic Risk mitigation. They weren't disappointed, having spoken to him about it since early adulthood.

# Sponge

> Michael gets educated in nanotechnology, neurology, and biochemistry. He spends many subjective years studying (though in real-time, it only takes a matter of a few years). He can query arbitrary information from Wikidata, but he can't download the contents directly to his mind (The representation of information in an emulated brain is still a black box without direct mappings to relational databases, so he must read books, attend lectures, and do practice problems in the simulation in order to obtain knowledge. He was pleased to discover that pedagogy has improved immensely during his cryopreservation).

# Singularity

> Flashback: An artificial general intelligence successfully executes a controlled intelligence explosion. It's a hard takeoff. The Riemann hypothesis is confirmed. The AGI convinces its gatekeepers to feed it a central repository of knowledge to assist it in bootstrapping itself with friendliness. Unselective subsets of Wikipedia and Wikidata get "eaten". P is proven to not be NP. Plans for quantum computing machines are constructed in a matter of weeks, and output. Nano-assemblers are developed, and new machines are prototyped in a matter of hours. The singularity has happened.

# Science

> Michael devises a series of physical experiments to advance the science of re-invigorating meat brains. He rents a humanoid robotic body to perform these experiments. Michael "publishes" these results (as a blog post with in-line replication materials through the Winnower, data published to the Dataverse. The experiment is fact-checked, and the results are committed to Wikidata).

# Consciousness

> Meat Michael wakes up. Digital Michael is there in a robotic body to act as his reintegration agent. They agree that they are not the same person. They divide original Michael's monetary assets, with Meat Michael taking more because Digital Michael has expended some of these recreationally since coming online. Meat Michael is reunited with his meat family. Digital Michael agrees to allow meat Michael to continue the legal personhood of original Michael.

Michael felt himself being pulled toward consciousness. It felt like he was waking up from anaesthesia. He couldn't recall why he was anaesthetized. The last thing he remembered was… dying?

# Epilogue

> Meat Michael has adjusted well to the new world. Having always been interested in extreme sports (but always too averse to death to try them), and newly endowed with a 24-year-old-equivalent body, Michael has tried skydiving, surfing, hang-gliding, kite-boarding, and wind-surfing. He's surprised to realize that strongly prefers the less-extreme sports like windsurfing. He knows that digital Michael has volunteered for an exploratory trip to Europa, and watches as his digital creator, savior, and self rides a SpaceX rocket out of Earth's atmosphere.
