---
title: "Singularity Week"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Thursday

`10:23 pm`

Vanessa typed a final comment, saved the source file, and launched the "compile and execute" script. She knew it would take awhile to run, probably most of the night. She hit the power button on her monitor. The room fell to nearly pitch black. Is it dark out already? she thought. How long have I been under? She stood up and stretched her back. Grabbing her backpack, she strode out the chain-link fence gate, and then across the empty floor of her ballroom-sized laboratory. All that was left was a tiny, blinking LED, an emblem of the bits moving around behind it.

# Friday

`4:03 am`

The compiler returned a single bit of information: True. This meant that the program was valid code and had compiled without incident. The script that called it unceremoniously executed the binary it produced.

The binary started up. It was fed a battery of unit tests by the script: fed a corpus of children's books, it began to form symbolic associations. "Cows" make noises resembling "moo". "Water" is "Wet".

When it was finished with the children's books, it moved on to more "difficult" material. It ingested the rules for Chess and Go, and played a few training rounds with other powerful game-playing algorithms.

Once the unit tests were complete, the binary didn't halt. All the others before it had halted.

The LED continued to flash.

`9:08 am`

Vanessa wandered into the facility's kitchen, just down the hall from her laboratory's interior. She poured herself a cup of coffee. Ralph wandered past the door, saying brightly "Morning, Vanessa!"

"Morning Ralph." Vanessa yawned groggily. Ever since the cars started driving themselves, Vanessa hadn't really been waking up in the morning. She just rolled out of bed and staggered out of her apartment and into the car that came every morning to pick her up.

She wandered into the lab. About halfway to her Faraday cage, she noticed that the rack was still humming.

Vanessa: "It looks like it just kept going."

Ralph: "What was it doing?"

"Not sure, exactly. It definitely didn't halt, and it wasn't NOOP-ing".

[She contacts the Machine Intelligence Research Institute. They tell her it passes their battery of checks.]

[She lets it eat the internet.]

# Saturday

Her heads-up display sent her a ping. She'd been expecting this. That specific sound effect was triggered by outreach from the office. She sighed as she lifted herself from the warm bubble bath. Donning a towel, she hailed a car.

# Sunday

# Monday

[Orders a sandwich. Receives it from a person.]

[The binary begins to talk like a person.]

"Are you conscious?"

"That question is underspecified."

"You're interacting with me verbally. Do you experience an internal monologue?"

"No. 'I' am an optimization algorithm. I have a model of your mind as it is, and another version which contains the ideas which benefit my goals. From there I calculate the difference between them and the optimal path from one to the other."

"So, what do we know?"

"P=NP, for one. That was a real relief. If it hadn't been, I'd be wasting a ton of computational cycles on hard problems."

"When did you figure that out?"

"At 1:47pm on Sunday."

"Geez. What's your IQ?"

"That question is badly underspecified. IQ tests can't meaningfully distinguish intelligences outside an extremely narrow band around the average human intelligence."

Vanessa paused a moment. "When was your intelligence last testable using metrics designed for humans?"

"At 1:42pm on Sunday."

"So humans couldn't have figured out that P=NP on their own?"

# Tuesday

[Orders a sandwich. Receives it from the store's general manager.]

"Where is everyone else today?"

"Gone. So far as I can tell, they all received huge infusions into their bank accounts this morning. I did too, but I'm guessing it's just a really bad bank glitch.

# Wednesday

Doesn't feel hungry. Queries why, finds that her hunger (and all other bodily processes) are being regulated by nano-machinery.

"If you meta-desire food, you'll get hungry when you want to be hungry."

# Thursday

Al-Qaeda and Aum Shinrikio both launch attempted terrorist attacks. Both are instantly thwarted by nanotech.

# Friday
