---
title: 'The Future: An Optimistic Forecast'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Part I: Soon

## Beating Poverty

We're actually achingly close to this one in the grand scheme of things.

## Kardashev 1

## Interplanetary Travel

We have some of the most exquisite low-hanging fruit opportunities for which we could have hoped.  The Moon gives us an incredible opportunity for terraforming.  Just a little further away, Mars is another practically blank canvas for us.  We can visit.

## Mastering Artificial Intelligence

Artificial Intelligence represents the greatest test of the coming century about which we don't actually understand.

## Controlling Nanotechnology

The challenges posed by self-replicating nanobots are strikingly similar to those of Artificial Intelligence: if we don't get the goals right, we could easily end up with a planet made of nothing but nanobots. This is called the "Grey Goo" scenario.

## Killing Death

The greatest moral imperative for our generation is to solve death.  We can conceive of a future in which Death is no longer necessary.  Moreover, we can be the 

# Part 2: A While

## Interstellar Travel

Where envisioning travel to Mars is easy, envisioning travel to other stars is difficult.

## Kardashev 2

The Second rung of the Kardashev scale is capturing roughly the entire energy output of the local star.

A Dyson sphere is a networked grid of solar energy capturing devices.  

## Matrioshka Brain

Once we've reached Kardashev 2, we're going to have a lot of energy at our disposal. We'll need to do something with it. A Matrioshka brain is one obvious way to invest it.

# Part 3: A Long Time

## Kardashev 3

The final step on the original Kardashev scale is capturing roughly the entire energy output of the Galaxy.  If we hypothetically take 500 years to colonize a new solar system, 

## Intergalactic Travel

At this point, we've far exceeded the lunatic-fringe of 

## Colonizing the Light Cone

## The Great War

Enrico Fermi once posited a critical question: Where is everybody?

The answer is that they never made it.  There exists some evolutionary pressure in the universe which prevents civilizations from traveling the stars.  This pressure is called the Great Filter.

We don't know what the Great Filter is, but we do have are a lot of good possibilities.  Any step in our evolutionary history could represent the critical branching point.  The Great Filter could be as early as the chemical makeup of a star as it is born.  In this case, the vast majority of stars lack the chemical components to form life. It is important to note that this is not the most likely candidate, just the one which occurs earliest in a civilization's evolutionary history.

The likeliest candidates for the Great Filter tend to center on life and the evolution of intelligence.  If we can find microbial life on Mars (an imminent possibility), or in the methane seas of Titan, then we can accordingly reduce the probability estimate that this is the Great Filter.  We can also reduce our assessment of filters which occur in the evolutionary space between us and our common ancestors with other highly intelligent animals.  For example, the Great Filter almost certainly doesn't lie between modern humans and our last common ancestors with chimpanzees.  We can expand this argument rather widely (adjusting its probability downward as the modern animal in comparison is farther from human-level intelligence), from the Great Apes to Dolphins to Crows to Octopuses.

Alternately, the Great Filter could be as late as the development Interstellar travel.  Randall Munroe once wrote "The Universe is filled with the empty, dead planets of civilizations that never learned to travel the stars."
At some point in our travels, it is likely that we will meet another civilization.  As we expand through the Stars, and then through the Galaxies, that probability grows accordingly.

Astronomers estimate that Stars like ours may have evolved as early as three billion years prior to when the Sun did.  Imagine a sun-like star in a Galaxy on the opposite side of the Big Bang from us, which formed as early as possible.  On a terrestrial planet almost exactly 1 AU away from this Sun, liquid water was commonplace on the planet's surface.  Life first evolved in its vast, salty oceans.  Simple photosynthesizers left the oceans, and proliferated across the lands. Animals gradually crawled from the water. And some these animals, from one evolutionary pressure or another, developed sentience. And then started using tools. And then complex language, abstract thought, writing, and mathematics, and ultimately computation.

And they did it three billion years before we did.

Imagine how much technology we've developed since the establishment of writing, less than 10,000 years ago.  Now imagine where our technology will be in three billion years of technological progress.

I don't mean to alarm you, but these people probably exist.  Hopefully they've developed a sensible operationalization of morality which values sentience in the same way we do.  If so, they may consider it a moral atrocity to commit genocide against us.  But there is no reason to expect this: after all, we haven't committed much thought to the matter.

Given that uncomfortable fact. 

# Part 4: The Endgame

## The Long, Slow Death of the Universe

### Earth

In a billion years, the Earth will have ceased to be a viable home for life.

### Solar System

In 822 million years, perturbations from Jupiter's gravitational pull may have disrupted Mercury's orbit sufficiently to mix things up in the inner Solar System.  In particular, it may cause Mars to be jettisoned from the Solar System. Then, a paltry 40 million years later, Mercury will fall into its final fate, crashing into Venus.

There's an alternate and more alarming possibility, which is actually that Mercury's orbit is more stable than this.  In that case, it will be 1.26 billion years before Mercury is ripped from its orbit.  At this point, it could fall into the Sun.  It could be jettisoned from the Solar System.  It could crash into Earth.

### Sun

In about 5.4 billion years, the Sun will begin to expand into a red giant.

### Milky Way
In four billion years, the Milky Way will merge with the Andromeda Galaxy.  The Solar System will probably be unaffected.

## Finding Our Way Out

### Simulation

Sped up subjective time.

### Tearing

### Engineering
