---
title: "A Celebration Homily"
---

# I.

Before, there was nothing. All was silence and stillness and empty. 'Empty' implies a place without things. Before, there was no place.

Then, with a cataclysmic noise, there was a place. A place with things in it.

It wasn't good or bad. It was just... stuff. Something. Hydrogen.

The stuff formed clumps. Huge clumps that burned. Stars formed and burned. Merged and collapsed. Novaed and Supernovaed. Spun around each other in simple dances. Inside, they transformed the stuff that made them. Took Hydrogen and forged Helium, Lithium, Beryllium, Boron.

Carbon.

As the universe continued to cool, smaller, cooler clumps of stuff formed. Rocks bumped into each other, accumulated into comets, asteroids, rocky little terrestrial planets, and fluffy gas giants.

And for nine billion years, nothing more happened.

# II.

But then, one day, the most interesting thing in the universe happened. Some atoms somewhere near an unremarkable yellow star accidentally linked up in exactly the right way, and became a replicator.

The replicator wasn't like the stuff it was made out of. Rather, the replicator could do something really special and interesting. It could take the stuff around it, and turn that stuff into other replicators, just like it.

Well, mostly like it. Sometimes, replicators grabbed molecules that were like the ones they were made out of, but not exactly the same. Most of the time, that meant the new replicator wouldn't work. Once in awhile, it meant the new replicator worked **better**.

Things continued like this for a while. Replicators replicated, occasionally stumbling upon a better formulation. This halting, accidental process built protections for the replicators: shells and excess reserves of their raw materials. More replicators, more replications.

Some replicators replicated one way. Some other replicators replicated another. The first way worked well, and those replicators' descendants (bacteria) got bigger. The second way worked well, and those replicators' descendants (archaea) stayed small.

Sometimes a bacterium would find an archaeon, and use it for parts to make another bacterium. It was a replicator-eat-replicator world.

And for another five hundred million years, nothing more happened.

# III.

But then, one day, a bacterium found an archaeon and tried eat the archaeon to use it for parts, and it didn't work. Instead, the archaeon lived inside the bacterium. The bacterium ate lots of things the archaeon could use to make more archaeon right inside the bacterium. The archaeon, in turn, threw away parts it didn't need, but that the bacterium did. That saved the bacterium all the trouble of making those things itself. It was an unexpected and beautiful relationship.

Together, the bacterium and the archaeon had formed something new. The first complex life.

Everything living thing that we can see with our naked eyes is descended from this life. You and I are both its grandchildren.

# IV.

I don’t expect humanity to survive much longer.

Often, when someone learns this, they say: "Eh, I think that would be all right."

So allow me to make this very clear: it would not be "all right."

Imagine a little girl running into the road to save her pet dog. Imagine she succeeds, only to be hit by a car herself. Imagine she lives in agony for hopeful moments, only to die.

Though you may imagine this thing, you cannot feel the full tragedy. You can’t comprehend the rich inner life of that child. You can’t understand her potential; your mind is not itself large enough to contain the sadness of an entire life cut short.

You can only catch a glimpse of what is lost--when one single human being dies.

Now tell me again how it would be "all right" if every single person were to die at once.

Many people, when they picture the end of humankind, pattern match the idea to some romantic tragedy, where humans, with all their hate and all their avarice, had been unworthy of the stars since the very beginning, and deserved their fate. A sad but poignant ending to our tale.

And indeed, there are many parts of human nature that I hope we leave behind before we venture to the heavens. But in our nature is also everything worth bringing with us. Beauty and curiosity and love, a capacity for fun and growth and joy: these are our birthright, ours to bring into the barren night above.

Calamities seem more salient when unpacked. It is far harder to kill a hundred people in their sleep, with a knife, than it is to order a nuclear bomb dropped on Hiroshima. Your brain can’t multiply, you see: it can only look at a hypothetical image of a broken city and decide it’s not that bad. It can only conjure an image of a barren planet and say "eh, we had it coming."

But if you unpack the scenario, if you try to comprehend all the lives snuffed out, all the children killed, the final spark of human joy and curiosity extinguished, all our potential squandered…

I promise you that the extermination of humankind would be horrific.

And yet, humanity is dying right now, as I say these words.

Every single one of us is marching towards their deaths, and most are already resigned to it. Do you know how often a human dies? About twice per second.

Tick tick tick tick tick tick tick tick tick tick. Ten deaths. Too fast for an appropriately somber pause. Barely half a second to remember that each was a sapient person, kin, fellow heir to our great birthright and all our vast potential. Barely enough time to acknowledge each one, nevermind to comprehend who they were, nevermind to mourn. Tick tick tick tick tick tick tick tick tick tick. Ten more. And some think they can conceive of the worth of this world.

One hundred and fifty thousand humans die per day.

One million humans die per week.

These horrors are literally incomprehensible.

And look at the state of those of us who are alive. How many of us are depressed? How many of us are lonely, and struggling to connect with someone, anyone?

The horrors levied against the living sometimes rival death itself. Right now, people are being tortured, abused, and raped. People are being ravaged by disease and dementia through no fault of their own. Every single one of us is aging, we are all condemned to waste away in our own skin, decaying until our minds falter and our bodies give out at last.

Do not get me wrong. If we can be happy, if we can enjoy our fleeting time—then we are sparks of light in this world of darkness. Despite the lovecraftian suffering around us, we are able to make friends and tell stories and laugh and forge lives worth living. The potential for good within us far outweighs the suffering. I have never once regretted, for a moment, that we exist, that we are here to carry the torch of humanity forward into the future.

But make no mistake, we carry that torch through darkness.

Tick tick tick tick tick tick tick tick tick tick.

Humanity is dying as we speak, and while we may one day have the opportunity to put an end to disease and death, we are far more likely to destroy ourselves than to cheat those ancient reapers.

Read your histories. How well do humans respond to the great challenges; we who tried to build a communist paradise and slaughtered millions, we who tried to build a capitalist paradise and built a blind machine that exploits weaknesses in our minds to increase our consumption? How close to the brink did our species come, when we discovered the secrets of the atom? How long did we teeter on that edge?

We are humanity, and our story is not some fairy tale where the plucky heroes are destined to survive. We are just one species in a cold and uncaring universe, rising up from the bottom; the dumbest possible civilization capable of inventing the technology we possess. We face the future blind and barely able to coordinate.

What, truly, do you think are the odds that an intelligent species selected at random survives long enough to gain the stars? What are the chances that nature never once in their long history presents them with a challenge that is too difficult? For this is not a storybook, and the challenges are not calibrated to our capabilities.

What are the odds that we’ll survive every single threat on the horizon?

If we want to make it out of here alive, we have to avoid totalitarian lock-in, civilizational collapse, catastrophic wars, biological terrorism, nanotechnological catastrophes, misaligned intelligence explosions, and all the risks we haven’t even noticed yet.

What are the base rates, do you think? How many civilizations ever manage to survive their homeworld and fill their galaxy? What are the odds we can dance the deadly dance with nature, and never miss a single step?

Because I’ll tell you this:

When we look up at the night skies, they are empty.

And this is not a fairy tale.

And we’re likely to lose.