---
title: "A Gentle Introduction to the Simulation Argument"
---

# Introduction

```{r, results='asis'}
source("infobox.R")
infobox(list(
  "Status" = "Incomplete",
  "Last Revision" = file.info("AGentleIntroductionToTheSimulationArgument.Rmd")$mtime
))
```

Films like the Matrix and the Thirteenth Floor have introduced the idea of the simulated world into the modern science fiction audience. These films, however, contain the kernels of ideas form the basis for a very real ongoing philosophical dialog. This dialog was launched by Oxford University Professor of Philosophy Nick Bostrom with his paper, _[Are We Living in a Computer Simulation?](http://simulation-argument.com/)_ [10.1111/1467-9213.00309] In it, Bostrom builds the logical basis _the simulation argument_. The argument, in short, is that one of these propositions is true:

1.  Civilizations don't survive long enough to create simulations, or
2.  Advanced civilizations can create simulations, but don't, or
3.  We are (almost certainly) in a simulation.

For its simplicity, it belies a complex tree of possibilities for reality. Let's unpack each one.

# Civilizations Don't Survive Long Enough to Create Simulations

Moving through the propositions in chronological order, we begin with the gloomiest. It may be the case that civilizations simply don't survive long enough to develop the technology to create complex simulations. (Though the argument doesn't mandate that the civilization in question be human in origin, let us assume for simplicity that humans are effectively alone in the Earth's [light cone](https://en.wikipedia.org/wiki/Light_cone).) This is fundamentally a statement about the Great Filter: if this is true, there exists a late filter (that is, one humanity has not yet encountered).

# Advanced Civilizations Can Create Simulations, but Don't

There may be some logical reason that capable civilizations elect not to simulate themselves. For example, they may be uninterested in counterfactual historical questions; in other words, they may build simulations, but design them to simulate their present exclusively. This seems to me to be the least likely scenario. Simple Simulations are already commonplace. We use atmospheric simulations to predict weather days in advance. We use statistical simulations to explain and predict social phenomena. We simulate physics for a variety of [recreational](http://universesandbox.com/) and [research](http://www.fromquarkstoquasars.com/researchers-model-birth-of-universe-in-mega-cosmological-simulation/) purposes. Most tellingly, we build simulations of humans, and run and modify them [exclusively for fun](http://www.thesims.com/). If there exists a reason that our civilization should not build complex simulations of itself, we haven't realized it yet. And even if we did, there's always some asshole who won't care and will do it anyway.

# We are (Almost Certainly) in a Simulation

This proposition is also called the _simulation hypothesis_. If humanity developed the technology to build complex simulations, and then used it to simulate itself, it probably wouldn't do it just once. It would do it every time it had a reason to do so. As computational costs diminish and energy availability expands, the resources to simulate the entire history of humanity would fall to levels individual might practically be able to afford. In short, we should simulate many orders of magnitude more humans than will ever exist in the Ur-universe. Note the stipulation, "_almost_ certainly." This is the sole point at which there exists a gap in propositions of simulation argument. It could be that we really are living in an un-simulated universe, and that we possess the potential to develop ancestor simulations. Owing to the This is a vanishingly small possibility. Consider that at this moment in subjective history, on the order of 100 billion humans have ever lived. Now, consider that a simulation of human civilization (of the type with which we're concerned) will contain between 1 and _n_ intelligent agents (where _n_ is greater than or equal to the size of the human population).

# What if it's True?

We can infer some interesting properties of the Universe, which in turn gives us testable predictions about cosmology [10.1140/epja/i2014-14148-0].
Weatherson Discusses, Accepts that he is a Simulation [10.1111/1467-9213.00323]
Bostom clarifies that Bostrom does not accept that Bostrom is a Simulation [10.1093/analys/anp063]
Bostrom Patches the Argument [10.1093/analys/anq107].

# References
