---
title: "Some Alternatives to Universal Basic Income"
---

# The Problem to Solve

Let us assume that automation will supplant large portions of the labor market for humans in the coming century. These former workers will only be able to minimal, impoverished lifestyles on the generosity of their family, friends, or local institutions. (Is this True?)

# Plugging the Dam One Hole at a Time

The current approach to dealing with long-term unemployment is to address it with a raft of progressive welfare programs. Injured on the job? Unemployment! Kids hungry? WIC! You're Hungry? SNAP! Don't get paid enough? EITC! The rent is too damn high? Public Housing!

Now, I am not opposed to any of these programs, either in principle or practice. I am, however, deeply concerned about the mindset that leads to their formation. There are many, many ways that a person can fall through the cracks of society. Wherever we find a crack, we build a program to catch those who tumble through.

It's paternalistic. A person benefitting from a variety of welfare programs may be entirely capable of lifting herself out of poverty, but to do that she may need something the government doesn't yet have a program to provide. By offering any of these targeted programs, the government is spending some amount of money on her behalf, effectively saying "We know better than you know what you need."

The impetus for this kind of policy is, basically, to protect government money from funding drug use.

It's incomplete.

# Retraining

While the tech community seems to be coalescing around the concept of Universal Basic Incomes, the political community is trapped in a conversation about job retraining.

The gist of the argument is that the government needs to provide the programs and tools to help people transition from jobs that are outsourced or automated to jobs with more longevity.

Old Workers Don't Transition, They Die. The labor market evolves away from automation by firing the employees who relied upon those jobs, and watching them die. New laborers entering the market simply avoid those industries for which labor is being automated away. (Is this True?)

# A Negative Income Tax

One problem with Universal Basic Income is that there are a variety of terms for it. Besides "UBI", there's also "Guaranteed Minimum Income".

And then there's the Negative Income Tax.

# A Fully Planned Economy

One possible solution is a fully planned economy. We could consign 

This is a bad idea.

# An Exponential Economy

Another possibility is that by the time we need Universal Basic Income, we no longer need Universal Basic Income. Here's how that works:

The population of humans grows according to some curve. Following some event like a technological singularity, the availability of most resources grows vastly faster than the population of humans. Accordingly, each generation controls considerably more wealth per capita than the previous.

The sort of singularity which could pring this about is the advent of Atomically precise manufacturing.

While this sort of utopia is a possibility, and one which I would hope to steer the future towards, 

# The Likeliest Future