---
title: "Bootstrapping"
---

# Or, In Case of X-Risk, Press Button

There's a button labeled "In case of X-risk, press button." One day, an existential risk occurs which all but certainly will destroy all life on Earth (so, Grey goo or celestial catastrophe). The button gets pushed.

A signal is sent to the Moon. A computer calculates the distances to the nearest star systems, and the optimal routes given the current locations of the planets, the sun, and the other systems. A specially-designed canon begins to fire small canisters in the directions of these routes.

All life on earth is extinguished. The Universe is dead again.

The canisters travel through interstellar space. There is no hurry: no one is awaiting their arrivals.

The first star system to catch its canisters begins to pull them toward its star. Some fall in. Some fall on gas giants. A few fall on terrestrial planets. These are eaten by acid rains.

Another star system catches its canisters. Again, they are destroyed. And another. And another.

And then, one system catches its canisters, and a few fall onto a terrestrial planet. It has liquid water and abundant carbon dioxide. The canisters that land there break open on impact. This releases the replicators.

Each replicator was predicted by a simulation to be able to replicate under certain conditions, on planets with certain chemistries. Some of them do well here.

These replicators are error-prone. In addition to self-replicating, they also evolve. Over many generations, they begin to stumble upon new strategies for increasing their probability of successfully replicating.

All these replications begin to have important side-effects. With much of the atmospheric carbon locked into organic compounds produced by replicators, Many years pass with many replicators unable to replicate because they lack the carbon to do so. Finally, one mutant replicator discovers it can eat other replicators, allowing it to self-replicate, and releasing carbon dioxide at the same time.

A billion years later, some intelligent species bungles its way toward an existential catastrophe. Luckily, someone had the foresight to build a contingency plan for the Universe.
