---
title: "Defining Self-Concept"
---

Kaj Sotala [found a strategy for solving his mental health issues](http://kajsotala.fi/2017/07/how-i-found-fixed-the-root-problem-behind-my-depression-and-anxiety-after-20-years/) in the the concept of *self-concept*.

I have some self-concepts which I wish I could dissolve.

### I am a Liar

At some point in my relationship with my significant other, I confessed something to her of which I was not proud and she was not aware. I won't say exactly what it is, but it's completely inane, like the overwhelming majority of ordinary dirty-little-secrets. The important thing was that the result was undesirable, a crushing blow to our relationship that took years to heal from.

At no point had she confronted me about this thing. At no point had I claimed that I didn't do this thing. I had [not lied explicitly](https://wiki.lesswrong.com/wiki/Not_technically_a_lie). However, in not being forthright about it, and taking steps to withhold this information, I had been lying by omission. It was many years before I could even acknowledge that this was a thing, let alone that I had done it and had been wrong to do.

I want to be someone who is reliably honest, but at the same time, keep the secrets I've buried for my adult life. In other words, I want to be as honest as possible in the future, while maintaining the the secrets that, were they revealed, could threaten the foundation of the lifestyle I currently enjoy. So, is it possible to build self-concepts to which you have strong, on-going counter-examples?

## Affixing examples to other self-concepts

My first thought for a strategy to accomplish this is to find another reliable self-concept to which I might affix this example.

### I am a Secret-Keeper

This however, is simply re-casting the lie-by-omission as secret-keeping. Secret-keeping seems like a noble and desirable skill,

## Accepting Your Counter-Examples
