---
title: "Do Not Overvalue Transparency"
---

Suppose there is a public health intervention that is both unbelievably cheap (say, $1.40 to administer) and unbelievably effective (100% of people who receive it live, and 50% of people who don’t receive it die). It’s administered to newborns, so we can say that more or less every life saved by the intervention is an entire life that would not have been lived (save for some small fraction of a DALY). Since the intervention reduces fatalities from 50% to zero, we can safely estimate that, on average, donating two doses ($2.80)  will save approximately one life.

Now, let’s suppose that the charity which has discovered this intervention begins administering it, but they’re really really bad at it. They take 99.9% of donations and put them towards overhead, fund-raising, staff salaries, bonuses, the annual holiday party… basically everything donors hate the idea of their money being spent on. 

Here’s the thing: if we can infer that the intervention is that effective and that cheap, independent of the charity, then we can figure out that for a $2800 donation, 99.9% (or $2797.20) doesn’t pay for interventions, and .1% (or $2.80) does.