---
title: "Evolutionary Quines"
---

The emergence of self-replicating molecules--a non-living precursor to life--is the most likely candidate for the Great Filter. To illustrate the logic behind this conclusion, let's translate the problem into a analog upon which we perform experiments and direct analysis. In computer science, a [_quine_](http://www.nyx.net/~gthompso/quine.htm) is a program which "self-replicates" in a certain sense. That is, it emits exactly its own source code. Consider the following quine (the shortest I could find), written in Python:

<pre>_='_=%r;print _%%_';print _%_</pre>

That's 29 Characters, each of which is necessary and irreplaceable to make the quine work.  11 of those characters are unique. Therefore, we could compress this program by encoding it into a characterset which used only [latex]lceil log_2(11)rceil=4[/latex] bits per character.  This step is fairly generous: for contrast, the standard characterset for strings is ASCII, which contains 256 unique characters, requiring 8 bits per character. Now, in our maximally dense characterset, the quine is an ordered sequence of [latex]frac{4bits}{1char}*frac{29char}{1quine}=116bits/quine[/latex]. Now, suppose we flipped a coin 116 times. (Coin-Flipping is a [surprisingly excellent](http://www.stat.columbia.edu/~gelman/research/published/diceRev2.pdf) source for randomly-selected bits.) If we map heads to 1 and tails to 0, the probability that we generate our quine is exactly [latex]frac{1}{2^{116}}[/latex] (or if it helps you visualize it in base 10, approximately [latex]10^{-34}[/latex]. If we don't compress our alphabet to the minimum integral bit density, that probability drops to [latex]frac{1}{2^{232}}[/latex], or about [latex]10^{-69}[/latex]. To illustrate how unlikely this is, Scott Alexander [recently used a clever device](http://slatestarcodex.com/2015/08/12/stop-adding-zeroes/) which I am now shamelessly going to steal. Imagine a researcher in a laboratory. Now imagine...

> [...] a tornado roars into the laboratory. The researcher is sucked high into the air. There he is struck by a meteorite hurtling through the upper atmosphere, which knocks him onto the rooftop of a nearby building. [...] His corpse is flung into the street nearby. As the rubble settles, his face is covered by a stray sheet of newspaper; the headline reads 2016 PRESIDENTIAL ELECTION ENDS WITH TRUMP AND SANDERS IN PERFECT TIE. Well, the per-second probability of getting sucked into the air by a [tornado](https://what-if.xkcd.com/19/) is 10^-12; that of being struck by a [meteorite](https://what-if.xkcd.com/19/) 10^-16\. The chance of the next election being [Sanders vs. Trump](http://www.predictwise.com/politics/2016demnomination) is 10^-4, and the chance of an election ending in [an electoral tie](http://fivethirtyeight.com/features/new-polls-raise-chance-of-electoral-college-tie/) about 10^-2.

Multiply all these probabilities together, and you get [latex]10^{-34}[/latex], the _same probability_ as randomly assembling a quine _under the most convenient circumstances possible_. (Incidentally, [Alexander's original example](http://slatestarcodex.com/2015/08/12/stop-adding-zeroes/) mapped out a probability of 10^67, much closer to the more natural and less convenient scenario of using the full ASCII charset). In general, the number of planets in the universe is [estimated](http://www.atlasoftheuniverse.com/universe.html) to be around [latex]10^{22}[/latex]. So the probability of ANY planet in this universe constructing a quine by flipping coins is something like [latex]10^{-12}[/latex]. I hope the last sentence sounds strange to you. Planets don't flip coins. Flipping coins can't, by itself, generate an executable computer program. More intrinsically, there are some important sources of non-randomness in actual evolution. The distribution of Carbon, Hydrogen and Oxygen in a planet's environment, for one. Lots of things are wrong with the model, but the method it uses and probabilities it exposes are illustrative and useful. The most important piece of the analogy, however, is the qualitative _algorithm_. Likewise, thermodynamics is a reasonable source for random atomic activity, which was the only driving force for the creation of anything in entire the Universe. However, in the moment that first, fragile replicator was created, the most interesting thing in the history of the universe occurred. Suddenly, there was a _new algorithm_ for building molecules. And all molecules which descended from that first replicator were generated using this new algorithm. Thus, subsequent evolutionary adaptations may have required discrete changes to the molecular structure with higher information complexity, but generated those changes using a FAR SUPERIOR search algorithm than the random algorithm which generated the replicator. To return to our quine, let's be generous and say that the next candidate for the Great Filter requires just one bit more than was required to build the quine, so 116 bits of information. The algorithmic complexity to construct the quine randomly was [latex]O(2^n)[/latex], where n was the number of requisite bits. The algorithmic complexity to _adapt_ the quine is much smaller. In all of these calculations, we have an important piece of missing information; a variable where we need a constant. That piece of information is the complexity of the simplest self-replicating molecule. If it were arbitrarily small (say, a [methane](https://en.wikipedia.org/wiki/Methane) molecule) I would have to pare back my probability estimates considerably. But we know that methane is not self-replicating. The prevailing hypothesis is that the first replicator was most similar to a strand of modern RNA, to which ambient molecules would affix themselves and then detach when they had formed the complete strand. There's a strong environmental component which I'm neglecting here. In order to self-replicate, the first replicator needed to be in an environment which was rich in assembled constituent molecules, something that is unlikely in itself.

Quines have been identified as a [basis for models of evolution](http://www.uncommondescent.com/biology/the-quine-dilemma-of-evolution/) before. The problem with this approach is that the means of error production in a quine must be explicitly written into the quine itself. In a true evolutionary situation, errors in the quine would be as much products of the environment as they would products of the replicator itself.
