---
title: "Mitigating Food System Shock"
---

# Introduction

Food crises are not one-solution-fits-all disasters. Much depends on the circumstances under which a food crisis occurs. If the crisis is caused by a blight, the survival strategy we employ should not rely upon different strains of the same crop. Likewise, if it affects the growing environment of a large agricultural region or regions in some detrimental way, we cannot rely upon any crops coming from this region. Accordingly, a generalizable plan must employ a multi-pronged approach, each prong of which is severable from the larger plan if it is rendered impossible by the circumstances. The plan must also be prepared to address the effects of the crisis across various time spans, from a mere season to permanent changes for the indefinite future, if need be. Most importantly, while new technologies are being developed more rapidly than at any prior point in human history, we cannot count on any specific technological breakthrough to save humanity. We must be prepared to work with only the resources we have on hand at present.

The first line of defense against mass starvation should be subsidies for crops that generate more calories. If a replacement crop yields more edible calories per area than the blighted crop, this could actually result in a net increase in the world calorie production. For example, if wheat crops were to fail, corn yields almost double the number of calories per square area per time. Potatoes nearly triple wheat's calorie yield. Thus, altering our farmed output would appreciably alter diets, but it need not threaten lives while the land is still arable. This approach also enjoys a legal advantage, in that Governments all over the world already do this routinely.

If the food crisis were triggered by a reduction in arable land, a cultural transition to vegetarianism might be required. Governments could order the slaughter of herds and flocks of living livestock, save for small breeding populations. In 1998, the Ecologist David Pimental estimated that feeding humans the grains consumed for meat production would increase the population the US could support to roughly 800 million. If we accept this assessment at face value, and roundly assuming a US Population of 300 million, this approach alone could mitigate a reduction in the caloric yield of crops of up to 62.5%. Moreover, it could be implemented immediately following a crisis, rather than the year following it. A growing variety of plant-based meat substitutes suggests that this is an increasingly palatable transition, even in the highly meat-centric diets of the developed world.

Another viable (if extreme) strategy is to provide economic incentives and social pressures to reduce caloric intake. Create incentives for practicing certain caloric-restriction diets, such as intermittent fasting. Biweekly fasting reduces an adult's calorie consumption by roughly 30%. Alternate day fasting (ADF) reduces it by 50%. While this would reduce the calorie consumption rate for dieters, it may also extend their lifespans, reducing the size of the effect across the population (though the net effect is still likely to be positive). Large-scale adoption of such a diet could result in small-but-critical decreases in the global calorie consumption rate.

Global food production currently outstrips demand, but the World Health Organization calls hunger "The single gravest threat to public health worldwide." This suggests that there exists a problem in the distribution of foods. Given the severity of a global food crisis, people may be relocated to places with better access to locally-grown crops in order to break down these distribution bottlenecks. This may be an especially effective charitable intervention, as moving a person to a food source need be done only once, but moving food to a person far from the source need be done repeatedly throughout the individual lifetime.

A famine will have far-reaching consequences for human evolution, but we possess the technology to reduce the suffering which follows these adaptations to induce less human suffering. Long term global population reduction may be necessary to prevent deaths by starvation. Accordingly a campaign to reduce the global fertility rate to below replacement rates might make durable contraceptives widely and freely available. Further long-term gains might be achieved by reducing lifetime mean caloric intake amongst then-children by instituting policies of growth attenuation therapy. By intentionally treating children with doses of estrogen, doctors can reduce a person's full adult height. This reduction comes with a desirable reduction in the number of calories the body metabolizes in normal day-to-day activities. If mass starvation were an imminent threat, governments could incentivize population reductions by more humane measures. For example, they could provide estate planning services and certain terminal luxuries (as explored by the Kurt Vonnegut story, Welcome to the Monkey House) to those willing to sacrifice their remaining lives.

All of these strategies will attract ardent enemies. However, there is reason to hope that we might be able stifle the cries of tyranny and the tides of anarchy. Jonathan Haidt describes the human inclination to collective action in the midst of a crisis as a "hive switch." Given a food crisis of global magnitude, even the most spoiled and impractical westerners will have to grudgingly accept that their lifestyles must change to survive.

The strategies I've presented here together offer an approach that is flexible, scalable, and robust to a variety of causes behind the shortage. However, it is ultimately incomplete. A complete plan must address the possible causes of the crisis, and their effects of each possible cause on each strategy. However, these provide a blueprint for a response which can be executed legally by existing institutions, and relies upon no future technologies to do so (i.e. could be implemented tomorrow).

If we venture past this barrier to speculate on the technologies that are *possible*, but untirely unpursued,

We can design a machine which mimics the process of photosynthesis by taking water, energy (in the form of electricity or heat), and atmospheric carbon-dioxide, and binding them into digestible organic molecules like glucose.

Plants absorb some amount of energy, and use it to bind water and chemicals in the atmosphere into more complex molecules, which store energy in their chemical bonds. Humans (and other plant eaters) co-opt this energy by eating the plant and digesting the molecules the plants have produced. Plants, however, are inefficient food production systems. In eating the plant, we also eat the plant's entire apparatus for any function the plant may perform other than storing energy.

Given an inefficient production system, the sensible response is to develop a more efficient one. In this case, that means replacing plants with industrial food-manufacturing machinery. 

Downsides: technical challenges. Relying upon energy opens the possibility that we could shift the burden of energy production onto existing, undesirable energy production methods (e.g. coal burning). Also, plants are self-repairing systems, while chemical production systems are not.

If we venture a little farther into the future, We could reduce the energy costs of humans by outsourcing the computation of human minds to digital computers.

The AI Impacts project has worked on predicting AGI by extrapolating forward from Moore’s Law. To that end, they’ve published some excellent articles on the brain capacities and the computed equivalents: Brain Performance in FLOPS, Brain Performance in TEPS, and Brain Information Capacity. One topic they haven’t yet broached is the brain’s power consumption. Let us assume that Whole Brain Emulations become computationally possible in the relatively near future (on the order of decades). How long will it be before computed human minds are more energy-efficient than biological brains?

The human brain consumes on the order of 10 watts. This is somewhat surprising when compared to, for example, an ordinary desktop computer, which will use about 350 watts. However, as processors have gotten predictably faster, they have also gotten predictably more energy-efficient. This is modeled by a relationship called Koomey’s Law. Roughly stated, "at a fixed computing load, the amount of power required to perform the computation will fall by a factor of two every year and a half."
