---
title: "Forecasting Lethal MIDs Between the Koreas"
---

# Introduction

> When will a lethal confrontation involving the national military forces of North Korea and either South Korea or the United States result in a fatality for either side?

In Political Science, a military event between two states which results in a fatality is commonly called a "Militarized Interstate Dispute", or "MID".

> North Korea frequently threatens to attack South Korea and the US (CNN, Reuters) and South Korea has responded with counter-threats and conventional preparations (The Telegraph, American Enterprise Institute for Public Policy Research). The two Koreas have been involved in scores of confrontational incidents, some of them lethal (The Guardian, Congressional Research Service).

# Base Rate

The Correlates of War project lists 351 Militarized Interstate Dispute Incident Participants which were either North or South Korea between 1993 and 2010. Of these, 11 resulted in fatalities. So, we should expect around 5 incidents in any three month period, of which only 3% result in fatalities, meaning a roughly 14% probability of any fatalities in the same three-month period.

This does not account for the fact the these probabilities should be correlated, and the incident history further mined for patterns (seasonality, annual events, etc.).

# 