---
title: "God's Sorting Algorithm"
---

# Introduction

Let us assume, for a moment, that some dogmatic form of Christian theology is true. In particular, let us assume that heaven and hell exist (by some definition of existence), and are accessible by the consciousnesses of formerly living persons. These consciousnesses are, by default, cast into hell. However, those which possess some set of beliefs gain access to heaven.

# God's Motivation

Imagine that you spawn a simulated universe which generates billions of morally-significant mortal agents. Upon their deaths, these agents can have their minds preserved indefinitely in some desirable state (heaven), or they can cease to exist, or they can be preserved indefinitely in some undesirable state (hell).

So, how do you decide who goes where?

We assign each agent some non-trivial moral significance, so a naive moral answer is to admit all the agents into heaven. This maximizes the one thing we know that we value: the moral welfare of the agents. If, however, we value the behavior of the agents more than their terminal welfare, we may prefer to leverage this afterlife system in order to extort desirable behaviors from them.

In order to enact this type of system, we must provide them some moral guidance. This can take any of a number of forms. For example, we can build altruism-reward systems into the agents' decision structures. Or, we can provide some very direct instructions. Or, we can provide access to the knowledge of who enters heaven and who does not, so the agents will emulate the denizens of heaven.

If we continue down the thread of Christian orthodoxy, we've opted for the "direct instructions" option. what desirable behaviors do we wish to extort? Well, trivially we want to maximize the moral welfare of all agents. Some broad, fuzzy directions like "Do Not Kill" and "Do Not Steal" should be a good start.

However, some problems have sprung up: the agents lack digital information storage, so your instructions are modified in retelling until they are written down many, many ticks later. The written instructions are complex, repetitive, contradictory, and occasionally quite wrong. Worse, some highly creative agents have constructed alternative instructions, claiming that their instructions are the ones which lead to heaven. Others have dismissed the existence of the transcendental realms entirely. However, they provide adequate direction to get some porotion of the population into heaven.

