---
title: "How Good Are Things?"
---

Scott Alexander recently [posted his perspective](http://slatestarcodex.com/2015/12/24/how-bad-are-things/) on what I'll call _social optimism_.

Tyler Cowen linked to it, with this note: "Arguably this post needs a broader sense of what makes a life valuable, still one of the more interesting blog posts of the last year." I think that the post deserves a slightly more nuanced and expanded handling than that.

Scott is basically making a list of stuff that makes life horrible, and then saying that the distribution of all this horrible stuff over the population results in a huge proportion of the population living lives that are basically awful. 

<script src="//repl.it/embed/DEB7/0.js"></script>

I have two criticisms. First, disasters love company. Someone whose life is miserable is considerably more likely to be the victim of other additional miserable circumstances. People in prison overwhelmingly tend to have cognitive disabilities (Citation Needed).

He sets up an important point: these horrible things are not all independent conditions. He describes two weirdly specific archetypes of someone whose life is miserable, with many factors which contribute to the misery, or at least suggest that it exists.

Second, he misses the possibility that happiness can be independent from these circumstances. Is it possible to be a rape survivor and have a life worth living? Is it conceivable that someone could have dementia and be Okay? Are any of these people happy?

So, what _does_ make life valuable?

Our lives are elaborate tapestries of good things and bad things. We occasionally get something truly wonderful, or truly horrible.

