---
title: "How Long Can We Accelerate at the Rate of Earth's Gravity?"
---

Earth's gravity causes us to accelerate downwards toward the Earth. It does so at a relatively specific rate: 9.8 meters per second per second. In other words, for every second that passes as we fall toward the Earth, our speed increases by 9.8 meters per second.

This is relevant to space travel in a wide variety of contexts, but one that isn't widely discussed presently is _emulating_ gravity. We could, hypothetically, begin accelerating a spacecraft toward its destination at the rate of Earth's gravity. This would cause our bodies to fall through the spacecraft at the same rate we fall toward the Earth. In effect, it would feel (with respect to gravity) like we were standing on the Earth's surface. This would be especially useful for inter-planetary travel.

Consider the [distance to Mars](http://www.space.com/24701-how-long-does-it-take-to-get-to-mars.html). At its historical best-case scenario, Mars was only 56 million km away from the Earth. Let us say that we could travel this distance in a relatively straight line between the two planets. If we were able to accelerate a spacecraft more-or-less constantly at the rate of Earth's gravity, we could cross the gap to Mars in just...

$$Displacement=\frac{1}{2}*Acceleration*Time^2$$

$$56000000km=\frac{1}{2}*\frac{.0098km}{sec.^2}*\frac{x^2 sec.}{1}$$

$$56000000km=\frac{.0049km}{sec.}*\frac{x^2}{1}$$

$$56000000km*\frac{1 sec.}{.0049km}=x^2 sec.$$

$$11428571428.6 sec.=x^2 sec.$$

$$106904 sec.$$

That's a lot of seconds! Why don't we convert it into something a little more manageable?

$$\frac{106904 sec.}{1}*\frac{1 hour}{3600 sec}*\frac{1 day}{24 hour}=1.24 days$$

I would be much more interested in a trip to Mars if it only took a day and a half to get there, and I could travel in the comfort of the equivalent of Earth's surface gravity. Unfortunately, traveling like this would also mean we arrive at Mars and a huge speed, and smack into it. So, to avoid turning ourselves into Martian pancakes, we need to decelerate en route. Specifically, in order to maintain Earth-like gravity the whole way there, we need to accelerate towards Mars for the first half of the trip, and then accelerate away from Mars for the second half. We could work this out analytically like we did above, or just ballpark it. It should take more than 1.24 days, and less than double that, so we'll just say it's something around 2 days.

This is a nice way to travel! Unfortunately, it's rather difficult. But assuming we've solved that problem, it carries a rather a hard speed limit: do it long enough and you'll hit the speed of light. So, how long is that?

$$\frac{299792458 meters}{sec.}*\frac{sec.^2}{9.8 meters}=30591067.14 sec$$

Or, to make it a little cleaner:

$$30591067.14 sec*\frac{1 min.}{60 sec.}*\frac{1 hour}{60 min.}*\frac{1 day}{24 hours}=354.06 days$$

Almost a year!  Now, this is a _theoretical_ limit.  As moving matter approaches the speed of light, the energy cost of pushing it to that speed approaches infinity. Never-the-less, if we could build propulsion methods that can provide this sort of acceleration, interplanetary travel could fall within the scope of a week-long vacation. And that would be awesome.
