---
title: "How To Save the Universe"
---

# Introduction

In his recent article "[Save the Universe](http://aeon.co/magazine/science/how-to-save-the-universe-from-certain-death/)," Michael Hanlon grapples with an uncomfortable truth about reality: we are doomed.  If intelligent life doesn't plan for its indefinite future, the universe will extinguish it. And then extinguish itself. And then there will be nothing. And there will be no metaphysical distinction between our universe and universes in which intelligent life never existed.

## Transcendence by Simulation

We could, in principle, construct a computer which simulated the Universe at a (very small) fraction of the energy costs of the actual energy costs of running the universe. We could thus expand the amount of subjective time during which we experience the Universe by a few orders of magnitude.  This "solution," however, is little more than a band-aid. Importantly, it's a decreasingly sustainable solution.

## Transcendence by Physical Transcendence

The solution described by Hanlon is fundamentally a physical transcendence.  What if we engineer the initial conditions of a different universe, and when it is adequately advanced in its development, we exit this one and enter that one? Note that this may not constitute a victory.  Consider the possibility that our universe is a simulation. Now, if this simulation was constructed to provide a "place" with more subjective time for the denizens of the ur-universe to live, transcending the simulation will us to enter a universe which is itself dying, and doing so sooner in subjective time than the simulated universe was. This would be a very bad thing.

## Transcendence by Information Transcendence
