---
title: Meditation
---

## The Science

It seems that there's a lot of it:

* https://en.wikipedia.org/wiki/Mindfulness#Scientific_research
* https://en.wikipedia.org/wiki/Research_on_meditation
* https://en.wikipedia.org/wiki/Brain_activity_and_meditation
* https://en.wikipedia.org/wiki/Neural_mechanisms_of_mindfulness_meditation

## What I'm Risking

Scott Alexander's [review of Mastering the Core Teachings of the Buddha](http://slatestarcodex.com/2017/09/18/book-review-mastering-the-core-teachings-of-the-buddha/) (more on that later) discusses the parallels between meditation and mental illness. Here is Daniel Ingram discussing the relationship between [Bipolar Disorder and the Cycles of Insight](https://www.dharmaoverground.org/es/web/guest/discussion/-/message_boards/message/105357?_19_threadView=flat). If we accept that these are risks (and [potentially severe ones at that](http://slatestarcodex.com/2017/09/18/book-review-mastering-the-core-teachings-of-the-buddha/#comment-547882)), what's the appeal?

I have no significant mental health issues of which I'm aware. 

So, if I'm willing to gamble my mental health, what else is there to be wary of? I've seen Enlightenment described in relation to one's feelings about death. I abhor it with complete and utter prejudice. If opinions on the topic of death are integral to elightenment, then I may be risking a choice between one of the core elements of my being and progress in meditation. Moreover, if this obstacle stands between me and a better state of psychological well-being, I will have an impossibly difficult choice to make: sane or morally consistent? It's this interaction that gives me real pause to [beginning a meditative practice](https://www.reddit.com/r/Meditation/comments/2pydaz/better_not_to_start_once_started_better_to_finish/).

At a more superficial epistemological level, I am a hard-core [material realist](https://en.wikipedia.org/wiki/Materialism). While this is a punchline of Buddhist wisdom AFAICT, it stands at odds with the Buddhist discussions of spirituality. This is not to say that it creates a logical contradiction (I don't know nearly enough about Buddhism to wade into an argument like that), but only that it requires a vocabulary that I currently cringe away from, if I don't lack it entirely.

## An aside on Language

What I mean by that is that I dislike talking about "spirits" or "realms" or "forms". From "spiritual" practicioners in the West, these come off as nonsense to me. From a more serious practicioner, they seem like words that are meant to [veil the things they represent](http://lesswrong.com/lw/nv/replace_the_symbol_with_the_substance/), and [should be tabooed](http://lesswrong.com/lw/nu/taboo_your_words/).

But there's an additional vocabulary-related problem. Much discussion of Buddhism is still deeply infused with terminology native to its languages of origin. Since I'm not in a hurry to learn Sanskrit, Hindi, Tibetan or Japanese, these words are going to carry little more significance to me than their phonetic content (at least at first). The fact that these words are usually explained in English with blunt terms like spirit, realm, and form (and then referred to using the original language) is a sad testament to English's poverty as a tool for exploring the idea-space of the mind. Perhaps we need a language with a much higher resolution in order to conceptualize these things properly.

I think that language might be [Ithkuil](http://www.ithkuil.net/). Thus, learning Ithkuil sufficiently to construct the Ithkuil vocabulary to stand in the epistemic location of Buddhist terminology is a project on which I intend to embark at some point.

## How I'm Tackling it

I started meditating by using [Calm](https://play.google.com/store/apps/details?id=com.calm.android) and [Headspace](https://play.google.com/store/apps/details?id=com.getsomeheadspace.android), and toying with using [Insight Timer](https://play.google.com/store/apps/details?id=com.spotlightsix.zentimerlite2).

However, after reading a bit, I'm beginning to believe that guided meditation would be an impediment to my progress. This is not a general observation: they may be incredibly valuable to some, and they may be important to me later. As of now, however, it seems like they're a crutch, enabling some behaviors I would like to train myself out of (especially clock-watching).

## How to Meditate: Introductory Readings
* [The Mindful Geek](https://themindfulgeek.com/) - It's a largely secular introduction to meditation.
* [Meditation, Insight, and Rationality](http://lesswrong.com/lw/5h9/meditation_insight_and_rationality_part_1_of_3/) [[Part 2](http://lesswrong.com/lw/5jj/meditation_insight_and_rationality_part_2_of_3/)]

* [Meditative States as Feedback Loops](http://slatestarcodex.com/2017/09/20/meditative-states-as-mental-feedback-loops/)

## How to **Progress**

"Buddhism" may or may not be a religion, but the practice of seems much more akin to skill-development than the common practices of the other religions with which I'm more familiar. (Scott Alexander [also pointed this out.](http://slatestarcodex.com/2017/09/18/book-review-mastering-the-core-teachings-of-the-buddha/)) Christianity, for example, doesn't really have an ordered hierarchy of skills through which one (layperson) progresses. Accordingly, I'm very interested and motivated by these advanced writings on building meditation-related skills.

* Ingram, Daniel. [Mastering the Core Teachings of the Buddha](http://integrateddaniel.info/book/) - I **really** liked this book. However, I am not really the audience for it. Rather, I plan to re-read this later. [See Also [Scott Alexander's Review Thereof](http://slatestarcodex.com/2017/09/18/book-review-mastering-the-core-teachings-of-the-buddha/)]

Stuff I mean to read:

* Yates et al. [The Mind Illuminated](https://smile.amazon.com/Mind-Illuminated-Meditation-Integrating-Mindfulness-ebook/dp/B01INMZKAQ/ref=tmm_kin_swatch_0?_encoding=UTF8&qid=&sr=) - At [the recommendation of Kaj Sotala](http://kajsotala.fi/2017/07/meditation-insights-suffering-and-pleasure-are-intrinsically-bound-together/).
* Brasington, Leigh. [Right Concentration](https://www.amazon.com/Right-Concentration-Practical-Guide-Jhanas-ebook/dp/B017JJOXQ6/ref=as_li_ss_tl?ie=UTF8&qid=1505098556&sr=8-1&keywords=Right+Concentration&linkCode=ll1&tag=slatestarcode-20&linkId=e7d22ca0de149894ff1d74a641d65a30) - Also at [Kaj Sotala's recommendation](http://kajsotala.fi/2017/05/books-that-have-had-the-biggest-impact-on-my-lifethought/).
* Wright, Robert. [Why Buddhism is True](https://smile.amazon.com/Why-Buddhism-True-Philosophy-Enlightenment-ebook/dp/B01MPZNG63/ref=pd_sim_351_2?_encoding=UTF8&psc=1&refRID=QK451BCNF43F12SB5R7Q) - While I found parts of Wright's The Evolution of God to be incredibly grating, it's historical perspectives on the foundations of the major Abrahamic faiths was unparalleled to anything else I've read on the topic. Moreover, the Moral Animal has been on my to-read list forever.
* [Joy on Demand: The Art of Discovering the Happiness Within]()
* [Transforming Your Self: Becoming Who You Want to Be](https://www.amazon.com/dp/B009Y5HS7K/_encoding=UTF8?coliid=I3E7JD8QQLZ4AQ&colid=3L0OD5J7BDGT0) - Last of [Kaj Sotala's recommendations](http://kajsotala.fi/2017/07/how-i-found-fixed-the-root-problem-behind-my-depression-and-anxiety-after-20-years/). I don't believe that I've ever been clinically depressed, but that doesn't mean my mental health can't be improved anyway. This strikes me as a sensible approach to adjusting characteristics that cause [regret](https://en.wikipedia.org/wiki/Regret), something we must all minimize.
* Hohwy, Jacob. [The Predictive Mind](https://www.amazon.com/dp/B00GV74Q7E/_encoding=UTF8?coliid=I3GJNGAXT99N5T&colid=3L0OD5J7BDGT0) - I'm curious about the interplay between the mind and behavior (both agential--what the mind is trying to accomplish--and kinesthetic--how the mind compels the body to do things that advance those goals). This seems like the best introduction to the field. Selected as an alternative to...
* Clark, Andy. [Surfing Uncertainty](https://www.amazon.com/Surfing-Uncertainty-Prediction-Action-Embodied/dp/0190217014/ref=asap_bc?ie=UTF8) - Supersizing the Mind has been on my reading list for awhile, so I was excited to see [Scott Alexander reviewing]() another of Clark's works.

Link Salad of Stuff I suspect will be valuable or interesting once I'm better at meditating

* https://www.reddit.com/r/streamentry/wiki/beginners-guide
* nabecker, [Practices outside of TMI methodology which accelerated TMI results](https://www.reddit.com/r/TheMindIlluminated/comments/6kn0ch/practices_outside_of_tmi_methodology_which/)
* [A phenomenology of meditation-induced light experiences: traditional buddhist and neurobiological perspectives](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3879457/)
* , [TWIM, a Crash Course](https://www.reddit.com/r/streamentry/wiki/twim-crash-course)
* [Reflections on a 10-day Silent Meditation Retreat](http://danfrank.ca/reflections-on-a-10-day-silent-meditation-retreat/)
