---
title: "Mother Planets, Life, and the History of the Universe"
---

# Introduction

Let's assume, for a moment, that there is an Early Great Filter (i.e., we've made it past), and that no mother planet in the Universe has evolved life. (Define a _mother planet_ is a planet upon which life has evolved, or will evolve.) If life is so unusual, the number of mother planets is given by the formula: $$N_n=1/(1-P)$$ where $N_n$ is the number of mother planets in the universe, and P is the proportion of planets in the universe born after a given mother planet (i.e. Earth). All else being unknown, what's the best guess for when in the life-cycle of the universe the Earth formed? Well, as with any point estimate from an otherwise unmeasured distribution, the best estimate is the median, or .5. Given this and P=.5, we can expect approximately two planets in the history of the universe to evolve life. It seems, however, that P is estimable, and decidedly not .5. In [On The History and Future of Cosmic Planet Formation](http://arxiv.org/pdf/1508.01202v1.pdf), Behroozi and Peeples estimate that P=.92. in other worlds looks like Earth had a head-start advantage over 92% of the other planets in the Universe. Thus, if the Earth was the only planet to evolve life so far, approximately [latex]1/(1-.92)=12.5[/latex] planets should be able to evolve life in the course of the Universe. If we alternately postulate that Earth is not unique among existing planets (i.e. life has already evolved elsewhere as well), we can modify the model to account for this fact: $$N_e=N_n/(1-P)$$ where $N_n$ represents the number of mother planets estimated to already exist. These estimates can span widely, from 1 (i.e. Earth is unique, as explored above) to $10^{22}$ (or the best estimate for the number of planets already in the universe). Now, it is important to note that the authors propose broadly two mechanisms by which terrestrial planets might form: one standard and one novel. If the novel formation mechanism doesn't bear out empirically, then the Earth was formed much closer to the conclusion of the universe's window of opportunity for the formation of life ($P\approx.2$). In this case, the predicted number of life-sustaining planets drops to 1.25.

# References
