---
title: "People Who Died in 2018"
---

But the people who make it onto these sorts of lists tend to be, well, popular. It seems to me that the public completely misses the deaths of people whom they should actually aspire to emulate, rather than celebrities who do things which amuse them. Accordingly, I've collected a short list of people who died in 2018 who did valuable things that most people will never hear about.

As all such lists, this is entirely subjective. [Many noteworthy people die](https://en.wikipedia.org/wiki/Category:2017_deaths) in [any given year](https://en.wikipedia.org/wiki/Category:Deaths_by_year). These are simply people who affected *my* life in some way, and whom I wish more people mourned. Please do no misconstrue a persons' inclusion on this list as an endorsement of any of their specific opinions or behaviors. I put them on the list for the reason that I give *in the list*. I'm not going to write extensive biographies or obituaries, just enough context to convey my reasoning for including them on this list. Accordingly, I won't tell you about the manner of their death unless it's salient to my inclusion of them. If you wish to know more, just follow the links.