---
title: "Power and Morality in Westeros and Middle Earth"
---

There are clearly good characters: Gandalf, Aragorn, Sam.  There are clearly evil characters: Sauron, Saruman.
Tolkein’s handling of morality isn’t overly simplistic.  Saruman rose through the ranks of Middle Earth’s few wizards to become the leader of the order.

Aragorn redeems himself early on within the story.  In the Fellowship of the Ring, Aragorn is faced with the unpleasant decision of whether to continue running from heritage, or to assume the responsibilities of the most powerful man in Middle Earth. He resigns himself to the role he must play in order to attain a safe and peaceful world. He is motivated by a genuine desire for peace.

I think the assessment that Middle Earth is a morally simplistic landscape stems from a direct comparison to George Martin’s world.

In George Martin’s world, we are presented with a group of people we are to believe are “the good guys,” namely the members of the Stark family.  But throughout the story, we are forced to watch the moral descent of the Starks; Jon breaks his vows (several times, in several ways), Rob takes up arms against the Crown, Arya turns revenge killing into her life’s work, Sansa verbally betrays and berates her family on a daily basis.  We see principled good exclusively in the character of Eddard, and even then with the caveat that he once betrayed his wife (though the exact nature of that betrayal is in dispute).

In contrast, Martin also introduces “bad guys,” the Lannisters.  However, just as the Starks are dragged downward, the Lannisters are morally promoted: Tyrion deals respectfully with the Starks, Jaime saves Brienne from being raped.  Even Cersei’s actions can be explained as we delve into her mind.  We only see principled evil in the character of Joffrey.

And to those principled characters, Martin offers exactly the same fate: unceremonious execution.
