---
title: "Prayer For Skeptics"
---

# Introduction

Why on Earth would you write a guide to prayer for people who don't believe in it?

# Human Identity

Humans benefit psychologically from attaching their identities to something bigger than themselves. Ideally, something so much larger, we can reasonably call it "infinite".

Where believers will tend to attach their identities to a thing they call "God", skeptics will employ much of the same language, while appealing to things like "the Universe". It isn't that they believe the Universe plays the same role which God plays in the life of believers; rather, it's just difficult to convey certain ideas without something really, really big and important against which to measure.

However, because the Universe does not occupy the role of God in the life of a skeptic, it makes a poor substitute as a target for prayers. I don't have a strong opinion on whether prayers need an addressee (and I can't find any salient research on the topic). I find it perfectly conceivable that a skeptic may successfully establish a useful routine of prayers addressed to no one at all. If you must address your prayers to someone (as I do, for what it's worth), there are some interesting options:

* You can [pray to the void](http://screamintothevoid.com/). In a way, this is the most honest addressee, as the value of prayer is changes within your own brain, and so targeting a celestial /dev/null minimizes the inclination to magical thinking.
* You can pray to yourself. Most of us have internal monologues.
* You can pray to [your future self](https://www.futureme.org/). This could be potentially quite useful, as the records of prayers recieved following sufficient time to forget the mind-state which led to them may aid in recalling useful or desirable mind-states later: happiness, elation, exhileration, and nostalgia all come to mind.

# Meditation



# Explicit Desire

We want things. One of the benefits of Prayer is that it opens a forum in which we can honestly ask for those things. However, in order to do so, we must first wrestle a small truth from our minds: out of all the entire universe, what things do we want so urgently that we should ask for them specifically. Until I am tasked with the job of asking for something, I'm usually not consciously aware of anything I that I do want so badly. Prayer forces us to turn a Universe's worth of "that would be nice to have"s into a short list of "I actually need this" or "I really, really want this".

# Gratitude

People who express gratitude tend to be happier people.

# The Power of Prayer

Ordinarily, when people speak of the power of prayer, they're usually invoking edge cases in which people in hopeless situations are prayed for, and gain some hope. The quintessential example is the medical patient who, after being prayed for by their entire church, is miraculously healed.

If you do not pray for someone, their condition will improve with some probability.
If you do pray for someone, their condition will improve with the same probability.
If you inform a believer that you are praying for them, they will tend to do worse.

Yup. Knowing that people are praying for them gives believers performance anxiety.

# Conclusion

Prayer is a wierd thing. 

# References
