---
title: "Probability is the Formalization of Belief"
---

# Introduction

When you say "belief," I hear something like "estimate of the distribution of probabilities over the entire possibility space for a particular topic." What on Earth does that actually mean? Consider an ordinary, fair, six-sided die. I believe that the die will

The next time you talk about a belief, think of it as sharing a probability estimate. Put an actual number on it.

Now, if your number is 0 or 1, you're either overconfident or your belief covers the entire possibility space. These are two different errors, and they both deserve some careful handling.

If you believe something with absolute certainty and I ask you for an estimate of your probability that that thing is true, you'll probably say 100%. You can make claims like that because we aren't keeping score. However, if I ask you to make a bet on that thing, you should be willing to take it. For example, if you're completely certain that a fair die roll will come up as a number other than 6, you should be willing to bet everything you own--after all, 100% probability means that there is literally no chance you're wrong. Now,

In the latter case, I can "believe" that a coin will come up either heads or tails with probability 1, but nobody's ever going to take a bet that it won't. Holding beliefs about an uncontroversial probability space (e.g. an ordinary, fair, 6-sided die will roll a number in the range 1:6 with probability 100%) isn't useful.

If, by contrast, your probability estimate is .5, you're probably not thinking hard enough (unless you're talking about beliefs that partition exactly in half, like the outcomes of a coin flip). Someone can "believe" that a fair die will roll a 6 with probability .5 because there are two outcomes: either it will or it won't. However, the (6, not-6) outcome-space is the wrong reference class. Instead, we should compare the probabilities of every possible outcome (1:6). Thus, I believe with confidence 1/6 that any given fair die roll will come up 6. If you meet someone who believes their probability of rolling a 6 is .5, you should make some bets with them.

When I say I "believe" something, it means I predict with greater than 50% probability that it is true.

# References
