---
title: 'Review: Through Your Eyes On Christmas Eve'
---

# Introduction

I hated Christmas for a very long time. I hated it for its commercialism. I hated it for its tawdriness. I hated it for its heroes. I hated just about everything Christmas is, and everything Christmas brings.

I wasn't always like that. Growing up as a middle-class child in a sprawling suburbia, I used to love setting out Christmas lights with my Dad, playing a role in the Church's pageant, going to the midnight Christmas Eve candlelight service. I loved the anticipation of gifts: Christmas was, after all, one of only two times in the year you can reliably get new toys, and maybe some scratch for whatever toys you didn't get.

But like all children, I wasn't long convinced of Santa Claus.  Like all intelligent 

It really started in the Christmas of 2004.  My father had suddenly and unexpectedly died from heart disease that November. He was 60.  I was 16.  Many of my cynical inclinations were strongly enforced by his untimely death.

For Christians, Christmas is the celebration of Christ's birth: the triumphant, foretold coming of the Messiah who would liberate the World, wrapped up in a healthy dose of modesty.

I've long liked Abney Park's unique literary perspective: It's a rock band that writes music from the perspective of a crew of Airship Pirates in a Steampunk Universe.  They're a foundational figure in the Steampunk Rock genre (and in my opinion, still the best in the class).  So I was curious when I heard about their 2011 Christmas Album, Through Your Eyes on Christmas Eve.

Right off the bat I have to give credit for the title:  When you mentally picture Christmas, what comes to mind?  If you imagine the nativity, I'll bet that you imagine it at night. If you imagine being at home with your family, is it Christmas morning, with piles of presents?  Or an afternoon Christmas feast?  For me, it's unquestionably the night of Christmas Eve.  To me, that time is more real and meaningful than all the other trappings of the holiday.
