---
title: "Should I Be a Vegetarian?"
---

# Introduction

I am going vegetarian. It’s not a late new year’s resolution or anything like that--more like a plunge into a lifestyle choice that I’ve been orbiting for a long time.[Vegetarians live longer](http://archinte.jamanetwork.com/article.aspx?articleid=1710093) (and vegans longer still, although pescetarians seem to live longest). Moreover, I have a compelling health-related reason for ceasing to eat meat: a minor-but-chronic medical condition which will be at least partly ameliorated by cutting meat out of my diet. But I’d be lying if I said that was my primary motivation. My primary motivation is moral: I believe that animals have a non-zero moral significance, and that we all have a moral obligation to avoid [reducing the well-being of other morally significant entities](http://reducing-suffering.org/how-much-direct-suffering-is-caused-by-various-animal-foods/).

My current opinion is that the most important determinant of moral significance is self-awareness (although I hold this belief weakly, if anyone wants to [persuade me otherwise](http://anthony.boyles.cc/contact/)). [Pigs may be self-aware](http://www.sciencedirect.com/science/article/pii/S0003347209003571). This means that the routine consumption of pig meat is extremely likely to be a [moral catastrophe](http://link.springer.com/article/10.1007/s10677-015-9567-7). When I think of eating pig flesh, I think of eating dog flesh. Anyone who’s spent an hour with me can figure out that I’m ([very much](https://scontent-iad3-1.xx.fbcdn.net/hphotos-xlf1/v/t35.0-12/11899273_10205252722053382_1304188206_o.jpg?oh=cd96c8fa7057417895b4b720ba623af3&oe=5699413E)) a dog-person. But dogs are, writ large, far less intelligent than pigs. They have always, unambiguously, failed the [Mirror Self-Recognition test](https://en.wikipedia.org/wiki/Mirror_test) (put a dog in an unfamiliar environment with a mirror to [observe this effect yourself](https://www.youtube.com/results?search_query=Dog+Mirror)). So my threshold for consuming intelligent animals is below the intelligence required for self-awareness. I don't know where, exactly, that threshold is for me, nor do I know where it should be to [prevent reflective regret](http://intelligence.org/files/TDT.pdf). However, I don't feel bad about eating commonly-consumed animals other than pigs. I have no great intuitive moral spasms while eating beef, poultry, or fish. Why, then, should I set the bar for my moral uncertainty so low?

Will MacAskill wrote [his dissertation](http://commonsenseatheism.com/wp-content/uploads/2014/03/MacAskill-Normative-Uncertainty.pdf) on moral decision making under uncertainty. He concludes that we should be _extremely conservative_ about making decisions with morally uncertain outcomes. To illustrate this in [his podcast with Tim Ferriss](http://fourhourworkweek.com/2015/11/22/will-macaskill/), he proposes a situation in which you're driving near a school, and need to turn a sharp corner. You could make the turn at 60mph--your car is able to do this without jeopardizing you or the car. But if a child is playing on the street onto which you're turning, you will certainly hit and kill the child. Alternately, if you made the turn at 20mph, you would spend considerably longer driving through that turn, but it would give your reflexes enough time to stop the car if a child were there, saving the child's life. So, even if there's a teeny, tiny probability that a child is around the corner, there's sufficient moral uncertainty to justify turning the corner slowly every time.

I’ve held these beliefs about the moral significance of the contents of my meals for awhile now, and failed to alter my patterns of decisions based on them. I have failed because I am very good at [Rationalization](http://lesswrong.com/lw/ju/rationalization/). For example, chickens are smaller than cows <sup>[[_citation needed_]](https://en.wikipedia.org/wiki/Wikipedia:Citation_needed)</sup>. A single chicken will yield enough meat for a minimum of one meal. A cow, by contrast, will yield enough meat for perhaps a hundred meals. If we value the lives of the chicken and cow approximately equally, we should obviously eat lots of beef and almost no chicken, since we derive one hundred times the calories for the same moral cost. I, however, do not value the lives of the cow and the chicken equally. If a chicken is less than 1/100 as significant as a cow, we should eschew beef in favor of chicken. If a chicken is more significant than that, we should abandon chicken for beef. So, which principled position have I adopted? Neither, I'm afraid. My true decision criteria wasn’t moral; it was hedonistic. I’ve been able to adjust my beliefs to these conflicting arguments to select my conclusion (I should eat _this meat dish_, for which I just happen to be in the mood). The moral gymnastics through which I put myself to make that conclusion were simply wasted effort. Rationalization is not a skill of which one should be proud. 

I'm lucky that my current diet side-steps a lot of thorny, ethical naval-gazing. I don't care for [eggs](http://blogs.scientificamerican.com/guest-blog/want-to-kill-fewer-animals-give-up-eggs-not-meat/), so I pass on dishes featuring them prominently. When I do buy eggs, I buy cage-free eggs.

To put this into perspective, I’m extremely excited about the prospect of laboratory-grown meat. I expect that by the time it begins to saturate the consumer market, I will no longer be gastronomically able to eat meat. This is a sacrifice I am currently willing to make_._ Implying (honestly) that I wasn't willing to make that sacrifice in the past. Which gives me pause: if I'm electing to make a relatively permanent change to my diet, Others have written about the [purchase of offsets](http://slatestarcodex.com/2015/01/04/ethics-offsets/) as an [alternative to vegetarianism](http://slatestarcodex.com/2015/09/23/vegetarianism-for-meat-eaters/). I find these arguments to be compelling and their conclusions to be broadly correct. Why, then, should I prefer to make this dramatic, uncomfortable change in lieu of that simpler, cheaper, and easier one? To answer this, consider a being which is vastly more intelligent and self-aware than humans. I'll call it [Macumber](http://gameofthrones.wikia.com/wiki/Macumber). I would probably consider this being to be vastly more morally important than the average human. Let us also assume that it loves the taste of human meat. One day it descends upon my house, reaches in, and grabs me. I cry out: "No! Please, no! Don't I also possess moral significance?" Macumber responds, "Of course you do. I've donated [$2838](http://www.givewell.org/international/top-charities/AMF#Costperlifesaved) to the [Against Malaria Foundation](https://www.againstmalaria.com/) to offset the moral effect of my consumption of you." I would not be greatly comforted by this offset as Macumber skewered me for roasting.

So, as a Macumber, I'm going vegetarian. I hope that wiser, more powerful, more important entities will chose similarly. I expect to fail. Eliminating an entire food group is hard. But I plan to [fail well](http://mindingourway.com/failing-with-abandon/), as close to the mark as possible, so that one day soon I'll eat my last meal with meat in it.

# References
