---
title: "Some Thoughts On Institutions And Assassinations"
---

# Introduction

I'm very interested in assassination.  Not the anecdotal, secret society, conspiracy theory kind of stuff, but looking at assassination as a viable alternative to warfighting.  Why slaughter an entire country (and endure countless casualties of your own) when you can kill just one person?  No matter how you feel about the issue, ethically it almost seems ludicrous not to ask the question.

In their landmark paper on the effects of assassinations on democratic institutions, Jones and Olken offer a logistic model demonstrating that assassinations are predictable events.  Among the predictive variables were polity score, national wealth, and the natural logarithm of population.  It is this last finding which concerns me—Jones and Olken give no theoretical explanation as to why the natural logarithm of the population is predictive (where the population is less so).  On the topic of population , they offer only this:

> [Assassination] attempts are more common in countries with larger populations. Doubling the population increases the probability of an assassination attempt each year by 0.35 percentage points. Though this may seem like a small effect, this implies that the leader of a country the size of the United States (population 300 million) is 1.8 percentage points, or about 75 percent, more likely to be assassinated each year than the leader of a country the size of Switzerland (population 7.5 million). This population effect is sustained in a multivariate context, so that it does not appear to proxy for per capita income, institutions, or war status. One natural interpretation is that the number of would-be assassins rises with a country’s population, whereas there is only one leader in each country. Therefore, the ratio of would-be assassins to leaders, and hence the probability of an attempt, increases with population.

This is a natural and appealingly simple explanation for the phenomena, save for the mathematical nature of the relationship.  Note that Jones and Olken offer the ratio of Citizens to Leaders as the causal characteristic, though they do not explore the concept in any great depth. Were there a linear relationship, this theory would hold without the need for dissection. This does not, however, explain why the relationship between population and assassination probability should vary logarithmically.

Consider two nations, A and B.  Let us assume that A is roughly twice the size of B, and that for all other meaningful characteristics, the two are virtually the same.  The statistical model Jones and Olken present suggests that the probability that the leader of A should experience an assassination attempt is .4% greater than the probability that the leader of B will experience such an attack.  However, the simple theoretical model suggests that this probability should be doubled.

How, then, do we rectify the divide between these modes of prediction?  I propose that the costs of assassination attempts counterbalance the benefits to the assassin, and that the existence of a larger body of citizens as potential assassins lowers the probability of an individual electing to commit an assassination attempt non-linearly proportionally to the difference in population size.

In its simplest form, the model is structured as a normal-form strategic game.  In this game, there are 2 heads of distinct states. Each head of state views the policies of the other unfavorably, and has exhausted traditional negotiation methods for changing the unfavorable policies.  Thus, the leader is faced with the decision to attempt the assassination of the opposing leader:

Where _L_ is the personal cost to the leader of being assassinated (_L_ < 0), and _c _<sub>i</sub> is the value of the concession that would be obtained if the opposing leader were deposed.  There are three pure-strategy Nash Equilibria: those two action profiles in which only one actor attempts assassination and the one in which they both do.  Played over time, leaders should decide to assassinate each other immediately (before the other can make the decision to do so), yielding the probable outcome that both leaders are assassinated.  However, we do not see this kind of brutal international politicking at the international level.  We must therefore refine the model.

At its simplest, the decision to commit an assassination is equivalent to a variation on the volunteer’s dilemma.  A player i prefers the leader of a given nation to be relieved of his or her office prior to the institutional end of his or her tenure (with value p).  That said, the act of forcibly removing said leader incurs a high cost, c.

Merge Jones and Olken with Archigos (parse out leadership title), Polity (dig into exec variables), COW Intrastate and Interstate warfare.

Relationship between leadership title and assassination,

Relationship between Executive characteristics and assassination,

Relationship between Intrastate warfare and assassination,

Relationship between Interstate warfare and assassination,

In broad strokes, this model captures the relationship between a population and its executive leader’s probability of experiencing an assassination attempt rather well.  That said, It degrades at the margins.  For example, in a state with a population approaching infinity, the probability of an assassination attempt approaches one (though the geographic distribution of such a population would severely limit the physical access required to execute an assassination attempt). I maintain that the marginal implications of this model are unimportant.

# References
