---
title: "Suicide Amongst Digital Agents"
---

# Introduction

What is the relationship between digital agents and suicide?

## Ems and Other Posthumans

## Nonhuman Digital Agents

# Death

In general, one of the goals of digitizing humans is to provide a means by which humans could continue to exist indefinitely, even if location in which we exist becomes unhospitable to our organic bodies. "Death", in this type of future, becomes optional. Moreover, it is ill-defined.

## Suicide

If a digital agent wishes to "commit suicide", then we can envision two senses in which the agent may attempt this. The first is simply to order the machine on which it is running to kill its own process. However, it is unlikely that this will constitute a permanent "death", as a sequence of mind states from throughout its lifespan will likely be recorded in more durable media, and a younger version of the agent could be launched from any of these.

Therefore, we can imagine a second, more extreme version of suicide in which an agent destroys all information which could be used to (at least easily) recreate it. By enacting this, an agent sharply reduces the probability that it will be relaunched from a younger version of itself. What would motivate such a decision on the part of the digital agent?

# Decision Theory

Consider a 

# As it Relates to the World Today

Currently, suicide (and generally death) appears to be analogous to the second form of digital suicide. We have no likely avenues to recover organic agents, regardless of whether or not that agent has achieved a mind state which inclines it toward suicidal action.
