---
title: The Foundation Upon Which I Stand
---

## Conquering Yourself

I aspire to improve my own faculties. I want to think harder, faster, and more deeply. I want to solve important and interesting problems. I want to be happier, and happy more often. I want to feel better, healthier, and stronger. I especially want to live longer. In short, I want to self-improve.

This is a well-worn path, but it is also a fraught one. The world of self-help seems like it is dominated by charismatic speakers and their ghostwriters. In the meanwhile, social science has begun to catch up with the projects of self-help. I was first introduced to this latter project (bringing science to self-help) by the [LessWrong community](http://lesswrong.com). However, my introduction occurred long after the heydays of [the Sequences](https://wiki.lesswrong.com/wiki/Sequences), and my first full readthrough was of the [compiled version](https://intelligence.org/rationality-ai-zombies/). In the time since the aforementioned heyday, the community has fractured, and a diaspora has emerged in its place. Pockets of LessWrongers and other Aspiring Rationalists have coalesced on [Twitter](https://twitter.com/lesswrong/followers), [Facebook](https://www.facebook.com/search/top/?q=LessWrong), [Tumblr](https://rationalist-masterlist.tumblr.com/post/130139930539/rationalist-masterlist), and the [dozens of blogs](https://wiki.lesswrong.com/wiki/List_of_Blogs) written by members of this community.

This blog is modeled as an entry into the latter group. I plan to perform a variety of experiments, some well-known amongst the community, and perhaps (eventuually) some more novel ones. In this way, the content of this blog should more resemble the writings of [Gwern](https://www.gwern.net/) or [Kaj Sotala](http://kajsotala.fi) than [Eliezer Yudkowsky](http://yudkowsky.net/).

## Conquering the Universe

But my ambitions extend very far beyond this. I identify more strongly with the futurist community than the Aspiring Rationalist community. Both were significant forces in the old LessWrong, owing in large part to Eliezer Yudkowsky's self-identification with both, and contributions to each. I feel that this isn't accidental: rather, that futurism is an epistemic [Schelling point](https://en.wikipedia.org/wiki/Focal_point_(game_theory)) for rationality. When one begins to ask about terminal goals, the distant future of the Universe is a *really* important consideration, and futurism is the school of thought equipped to engage with these questions in any meaningful and productive way. I plan to expand on this opinion in future post(s).

In late 2015, an (Un)conference called [Five Worlds Collide](https://www.facebook.com/events/1505431786437253/) was held. The five worlds were Effective Altruism, Quantified Self, Rationality, Transhumanism, and Artificial Intelligence. (The title was a nod to a [Short Story](http://lesswrong.com/lw/y4/three_worlds_collide_08/) by Eliezer Yudkowsky.) While I didn't attend, it sounds like something I wish desperately I could have. All five topics interest me greatly, as well as many similarly-aligned topics. So I'll also write about these.

## Learning to Win

I have, in the past, been a less-than-adequate blogger. I wrote lots but posted infrequently, obsessing about perfecting the content rather than submitting it to public scrutiny, and flinching away from it when I did share publicly. I don't have thick skin. I don't predict that this will be any different. Why, then, should I even try?

First, I'm modifying my platform of choice somewhat. In the past, I've used [Wordpress](https://wordpress.org/) and [Drupal](https://www.drupal.org/), both of which provide effectively infinte room for twiddling with the minutae of settings in lieu of writing. For the first time, I'm using a static-site generator ([Hexo](https://hexo.io/)). This doesn't remove the opportunity for obsessing about layouts and plugins and whatnot, but it does obscure it behind a layer of knowledge I don't feel any other strong compulsion to develop (in contrast to the CMSs, which I often used professionally as well as personally, and so had to know inside and out).

Second, I'm blogging pseudonymously. In the past I've blogged under my real name with no attempt at maintaining personal privacy. This, however, severely constrains which beliefs I'm willing to profess. I don't know if this will help. Even now, under the veil of anonymity, I'm wary of posting an exemplary statement for fear of being outed. Perhaps this concern will diminish as I'm not thinking about it explicitly.

Finally, and must importantly, I feel an urge to write, and hold a long-standing desire to do so. I expect that the cognitive benefits of writing are significant [citation needed]. My deepest explorations of the topics of interest to me were all byproducts of writing about them. And while I don't believe I've ever meaningfully contributed to a discussion on any of those topics, I hope to build my strengths up to (and beyond) the ability to possibly do so.
