---
title: "The Not-Quite Life-Changing Magic of Tidying Up"
---

# Introduction

Last year I jumped on a popular bandwagon and listened to Marie Kondo's Life-Changing Magic of Tidying Up. This book is billed as a solution to clutter, but also to busyness and unhappiness. If this sounds a bit oversold to you, join the club.

Kondo's basic thesis is that each and every one of your posessions must pass a simple litmus test: *does it bring you joy?*

# The Lifestyle that didn't Stick

Kondo outlines a procedure for tidying one's household. It is alarmingly radical. The gist is that one categorizes one's possessions into a small number of groups: Clothes, books, papers, komono, and sentimental items. When working on a group, take every item belonging to that group and drop it on the floor outside of its natural storage location. Then, when you've collected all the items in a single pile, pick up each one and ask "Does this bring me joy?" If the answer is yes, return it to its appointed home. If not, offer the item your gratitude, and place it in bag, box, or other container for transportation to the nearest thrift store, so it may bring joy to someone else.

I didn't even attempt this ritual. For one thing, the emotional logistics of performing this in a household for which you are not the only member are impossibly complex. Even if all the people involved were on-board about doing it, it's a ripe situation for hurt feelings and subversive joy-finding.

I did, however, begin to attempt to audit my posessions as I encountered them. And from this practice, I discovered that I am not a terrible packrat. I have some things that I don't need or want, and I collect those to go to the thrift store. However, I have a ton of things that don't bring me joy, but do bring me *utility*. I don't need to delight in the existence of a light bulb to understand that it was cheaper to buy a pack of six bulbs and store the extras until I needed them. Annoyingly, it seems to me that Kondo's philosophy has no room for such sensibilities.

# The Lifehack that did Stick

There was one wierd suggestion of Kondo's that really has genuinely stuck with me. She suggested that the way in which we store clothes is *wrong*.

A container (such as a drawer in a chest) is usually going to be a rectangular prism. Our clothes are irregular but flexible shapes. Accordingly, we should fold our clothes to fit the space.

Moreover, you should be able to access all distinct articles of clothing without disloding any other articles. You can accomplish this by devising a folding method which causes the clothes to occupy all of the space in one dimension of the drawer, and stands upright in the remaining two.

There is 
