---
title: "The Role of Government in Existential Risk Mitigation"
---

# Introduction

The existential risk mitigation ecosystem is predominantly composed of non-profits that are devoted to the task of studying existential risks.

Only the US Government is prepared to deal with certain types of existential risks.

# Near-Earth Objects

NASA’s [public catalog of NEOs with measurable cumulative impact risk](http://neo.jpl.nasa.gov/risk/).

NASA, DoD, ESA, SpaceX

# Supervolcanic Eruption

Catastrophic Global Climate Change and/or Ecosystemic Collapse

Global Climate Change is unequivocally a global catastrophic risk. However, arguments that it represents an existential risk to humanity are far more tenuous.

# Bioweapons (or accidents)

I’m going to classify all bioweapons and bioengineering accidents together, as the distinction doesn’t really matter once the germ is released.

The CDC, WHO

# Nanotech

# Artificial Intelligence

The one noteworthy exception is the Machine Intelligence Research Institute (MIRI), which was founded for the goal of building an artificial superintelligence, but has since pivoted to the goal of building a safe artificial superintelligence.

The White House [recently announced a series of workshops](https://www.whitehouse.gov/blog/2016/05/03/preparing-future-artificial-intelligence) to investigate the issue.

The prospect of an Artificial Superintelligence launched as part of a military campaign is a regarded as near-certain death sentence for humanity.

# References
