---
title: "What I Know About Buddhism"
---

I have a very close friend who has, over the last few years, come to self-identify as Buddhist. Independently, I have long intended to take up the practice of meditation. It seems like it [might have some desirable effects](https://en.wikipedia.org/wiki/Research_on_meditation). (Note that I'm not coyly understating my confidence in the efficacy of meditation: I lack sufficient confidence to make such bets.)

In response to Scott Alexander's [book review on Buddhism](http://slatestarcodex.com/2017/09/18/book-review-mastering-the-core-teachings-of-the-buddha/), I've decided to start my own investigation of it as a means for self-improvement.

I intend to write this in multiple passes

# Pass 1: I know nothing.

## History

I know effectively nothing about the history or traditions of Buddhism.

## Meditation Expectations

I expect that meditation will improve my ability to focus (e.g. work instead of opening Facebook every 10 minutes), to emotionally self-regulate (e.g. not lose my temper),

# Pass 2: I know little.

Readings:
* [The Mindful Geek](https://themindfulgeek.com/)
* [Mastering the Core Teachings of the Buddha](http://integrateddaniel.info/book/)
* [Deepak Chopra's Buddha: A Story of Enlightenment](https://www.comixology.com/Deepak-Chopras-Buddha-Vol-1/digital-comic/176453)
