---
title: "Why Did Trump Win?"
---

# Introduction

# The Time for Change Model



# It's the Economy, Stupid



# The Primaries

Primaries don't tend to have a huge effect on general elections. There are some unusual things about this one, however, that suggest they might have.

## Donald Trump

Donald Trump launched his campaign to great success, and more-or-less kept it. In that way, this primary strongly resembled the 2012 primary in which Mitt Romney took the top spot, and a variety of other Republican contenders each briefly peaked as the last best hope to dethroning Romney. All of them failed.

Trump wouldn't commit not to run as an independent. The game theory of this is interesting: as an independent, Trump would almost certainly have lost, but done so with a healthy portion of the Republican vote. In that way, he played chicken with the Republican establishment and it payed off.

## Bernie Sanders

Sanders claimed that he was the only candidate who could beat Trump's populist approach in the General Election. Many Democrats are now wondering if that could have been true.

# The Email "Scandal"

## The "Comey Effect"

FBI Director James Comey released an additional thousand emails collected from Huma Abedin's mobile devices and computers, which were seized in an investigation into Abedin's husband, Anthony Weiner. In 2011, Weiner accidentally posted a nude photo of himself on his public twitter feed, along with unambiguously sexual text addressed to another Twitter user.

Clinton's email's were one of only three lines of attack that Republicans successfully leveled against Hillary Clinton. Another was...

# Clinton's Health

The final point was...

# The Clinton Foundation

# "Musical Chairs"

All of the above factors contributed to Clinton's declines in the polls. However, what gets missed in this narrative is that Clinton experienced significant bounces in the polls, too. Clinton's numbers saw a significant spike following the DNC, while Trump's numbers took a serious dive, owing to a spat with the Muslim parents of an American soldier which was killed overseas. After a period of natural degradation, Clinton experienced significant bounces after the first and second debates, in which she is widely agreed to have beaten Trump rather handily.

Viewed in this light, Trump's win was a lucky happenstance of the moment in which the Election was held, as [Sabato's Crystal Ball Argues](http://www.centerforpolitics.org/crystalball/articles/in-2016s-game-of-musical-chairs-the-music-stopped-at-the-wrong-time-for-clinton/).

# White People Voted

Yup.

## Angry, Poor, Rural, Uneducated, Racist, Sexist, Male White People Voted

Yup.

As evidenced by the movement to Repeal the 19th Ammendment.

# Minorities Didn't Vote

Yup.

## Minorities Didn't Show Up

Uncertain. I can't find a reliable data source that indicates whether or not minority voters attempted to vote.

## Voter Supression

Voter ID laws.

Voter Intimidation. Following early reports of "election watchers" planning to garrison outside of polling stations, not a lot of coverage was devoted to anything these election watchers actually did.

http://www.newyorker.com/magazine/2016/12/12/the-real-voting-scandal-of-2016

# Third Party Spoilers

## Jill Stein

As Dave Wasserman [pointed out](https://twitter.com/Redistrict/status/804407177368715265), Jill Stein's votes tallies are large enough to flip back Clinton's lost midwestern firewall states.

* [Clinton lost Michigan by 10,704 votes. Jill Stein got 51,463 votes.]()
* [Clinton lost Wisconsin by 22,177 votes. Jill Stein got 31,006 votes.]()
* [Clinton lost Pennsylvania by 46,765 votes. Jill Stein got 49,678]()

Together, these three states consitute 46 Electoral votes. As Trump won with 306 votes in the electoral college, Stein dropping out and endorsing Clinton could have reduced Trump's edge in the Electoral College to 260, flipping the election. This triggered an outcry on the left, branding [Stein the Ralph Nader of 2016](http://theweek.com/speedreads/664953/jill-stein-officially-2016s-ralph-nader). While it's true that these margins seem to suggest a spoiled election, the implicit assumption is a little strong for my taste. Namely, the assumption is that Clinton would have won a huge proportion of those Stein voters. To flip Pennsylvania, for instance, Clinton would have needed at least 94.2% of Stein's voters.

While I suspect that at least that percentage would prefer a Clinton presidency to a Trump Presidency, I don't believe that these people would have voted for Clinton over Johnson, some other unknown far-lefty, or writing in "Bernie Sanders". However, [CNN takes this one step further](http://www.cnn.com/2016/11/10/politics/gary-johnson-jill-stein-spoiler/), arguing that Clinton might have won Florida with a small margin of Johnson supporters...

## Gary Johnson, Libertarian

Even if Stein could plausibly be called a spoiler for Clinton, it's important to note that we should counterfactually provide the same analysis with Gary Johnson. [Vox called him](http://www.vox.com/2016/8/3/12367358/trump-republicans-gary-johnson) "The most orthodox conservative in the race". Based on the close association between the Republican Party and the Libertarian Party, I claim most Johnson voters would sooner have supported Trump than Clinton. Accordingly, convincing Johnson to drop out would have led to a Trump victory.

Moreover, as Johnson uniformly garnered more votes than Stein, there's a more compelling case that had Clinton won, it would have been because Johnson was a spoiler for Trump.

## Evan McMullin, Independent Republican

Perhaps the most interesting third party candidate was Evan McMullin. McMullin presented himself as the only establishment Republican willing to run against Trump. However, he was hardly a well-established establishment Republican. A former CIA officer turned Congressional staffer, McMullin took it upon himself to run in ideological opposition to Trump. McMullin was also a devout Mormon from Utah, which made him a [viable candidate for that state's electoral votes](http://fivethirtyeight.com/features/how-evan-mcmullin-could-win-utah-and-the-presidency/).

It was clear that carrying Utah was still an extreme long shot for Clinton, even with McMullin in the race to split the republican vote. However, If the Democrats in Utah had coordinated an effort to vote McMullin instead of Clinton, they could plausibly have denied Trump Utah's six electoral votes. This, while a useful object lesson, does not represent a severe error on the part of the Democrats, as it was always unlikely to be a tipping point for the election.

## Other Candidates

Didn't matter. Like, at all.

# Voter Fraud

One confirmed case of voter fraud... for Donald Trump.

Perennially doesn't matter.

# The Electoral College

Yup. Clinton lead the National Popular Vote by more than 2 million votes.

# Que Sera, Sera

In [Tuesday shouldn't change the narrative](http://slatestarcodex.com/2016/11/07/tuesday-shouldnt-change-the-narrative/), Scott Alexander sensibly pointed out that no serious model gives Trump a negligible probability of victory, so a Trump victory is simply a matter of probability. Accordingly, our beliefs should not be greatly updated by the outcome. Rather, whatever narrative we would be telling in the wake of a Clinton victory, we should still believe all of those things.

The point is that all of these things are true, and none of them represents the "fundamental reason" or the "root cause" of the outcome of the election. Claiming that they are is the wrong way to view the election, and will only lead us to obsess about the minutae of personality and politics, when the truth is more banal: Trump got Lucky, Clinton did not.

# References
