---
title: "Cryonics Bibliography"
---

# Introduction

```{r, results='asis'}
source("infobox.R")
meta <- list(
  "Status" = "Incomplete",
  "Epistemic Status" = "Uncertain",
  "Last Revision" = file.info("CryonicsBibliography.Rmd")$mtime
)
infobox(meta)
```

This follows my self-education in Cryonics, specifically as I would have ordered these materials if I were to start from the beginning again. This is roughly ordered by technical difficulty: the less technical books are at the top, and more technical works follow at the bottom. At the end, I’ve also included a section of books I simply wouldn’t bother with at all, along with my notes about why they fall here.

## If you only read one thing...

* Read the Wait but Why post, [Why Cryonics Makes Sense](http://waitbutwhy.com/2016/03/cryonics.html).

# Why Should We Consider Cryonics?

Because living is awesome, of course!

* [The Open Letter on Cryonics](http://www.evidencebasedcryonics.org/scientists-open-letter-on-cryonics/) - There are a bunch of really smart people who openly affirm that Cryonics is a viable avenue to life extension.

* Robin Hanson - [We Agree: Get Froze!](http://www.overcomingbias.com/2008/12/we-agree-get-froze.html)
* Eliezer Yudkowsky - [You Only Live Twice](http://lesswrong.com/lw/wq/you_only_live_twice/)

# Who Does This?

Ted Williams is the most famous Cryonics case, but there's been a lot of long-form journalism on cryonics cases in the last few years.

* [What it took to get Ted William's Head Off His Body](http://deadspin.com/what-it-took-to-get-ted-williamss-head-off-his-body-1475054922)
* [What Really Happened to Ted Williams](http://www.si.com/vault/2003/08/18/348299/what-really-happened-to-ted-williams-a-year-after-the-jarring-news-that-the-splendid-splinter-was-being-frozen-in-a-cryonics-lab-new-details-including-a-decapitation-suggest-that-one-of-americas-greatest-heroes-may-never-rest-in)
* [The Girl Who Would Live Forever](https://motherboard.vice.com/en_us/article/the-girl-who-would-live-forever)
* [A Dying Young Woman's Hope in Cryonics and a Future](https://mobile.nytimes.com/2015/09/13/us/cancer-immortality-cryogenics.html)

# How Does it Work?

* *Wait but Why* - [Why Cryonics Makes Sense](http://waitbutwhy.com/2016/03/cryonics.html).

If you're interested in technical details of the procedure(s):

* [Cryonics UK Standby, Cool-Down, and Perfusion Procedures](http://cryonics-uk.org/download/Call-OutManual-2014%281%29-Apr.pdf)
* [The Oregon Cryonics Manual](http://www.oregoncryo.com/manual/manual.html)

# Will it Work?

We don't know, and anyone who says it will is vastly overconfident. But as Dr. Ralph Merkle once observed, "Cryonics is an experiment. So far the control group isn't doing very well."

## Good Criticism

Critics tend to light into the science behind it without having a good grasp of the mechanics themselves, and so rely on overly-simplistic and generally-flawed arguments like "ice crystalization ruptures cell walls." However, there are some actually-good critical articles out there:

* [The Faulty Logic of Cryo-freezing Dead People](https://deathbycosmos.com/blog/logic-of-human-cryo)

Perhaps the best criticism of cryonics is that it may not be the *likeliest* avenue to longevity. Critics of this stripe tend to gravitate toward an alternative procedure, known as...

## Plastination

* Gwern Branwen, [Plastination](https://www.gwern.net/plastination)

Plastination, regardless of whether it will work or is more likely to work than cryonics, is not currently commercially practiced on humans anywhere ([Bodies](https://en.wikipedia.org/wiki/Bodies:_The_Exhibition) exhibits notwithstanding). That reduces its probability of success effectively to zero (in the near future).

# How do I sign up?

As far as I can tell, there are only a few organizations world-wide doing cryopreservation. They are:

* [Cryonics Institute](http://cryonics.org/become.html)
* [Alcor Life Extension Institution](http://www.alcor.org/BecomeMember/index.html)
* [Oregon Cryonics](http://www.oregoncryo.com)
* [KrioRus](http://www.kriorus.ru/en)

And at some point in the near future...

* [Southern Cryonics](https://southerncryonics.com/)

## Paying for it

Cryonics is pretty expensive right now. That's due to an unfortunate confluence of social circumstances: it's often considered weird, and so isn't very popular. That means the demand can only support a few providers. That means that there are only a few locations where it can be done. That means providers must be prepared to jump through absurd legal hoops and transport your body rapidly following your clinical declaration of death. Not to mention the process itself is complicated, and time- and resource- intensive.

Luckily, there's an alternative way to pay for it: Life Insurance. Contact [Rudi Hoffman](http://www.rudihoffman.com/).

## Making Arrangements to Assure Your Cryopreservation

1. Move as close as possible to your Cryonics provider.
2. Live as safely as possible. One way to reduce your probability of cryonic success is to suffer traumatic injuries or to die in a way that leaves your body unrecoverable.
3. Carry a cryonic-preparation standby kit. See the [Cryonics Institute Standby Manual](http://www.cryonics.org/images/uploads/misc/Cryonics_Institute_Standby_Manual.pdf) on what to collect.

# References I Would Skip

There aren't a lot of people writing or talking about cryonics. If something I have read doesn’t contribute to the conversation (but seems popular enough not to ignore), it goes here.

* [Frozen to Life: A Personal Mortality Experiment](https://www.amazon.com/Frozen-Life-Personal-Mortality-Experiment-ebook/dp/B01371OE6O/) by D.J. MacLennan - This is a long and rambling personal narrative which has little to do with Cryonics itself and much to do with the life progression which led one person to sign up for cryonics. It's often interesting, and MacLennan has a very good grasp of the philosophy and science behind cryonics (despite being an expert in neither). However, the circumstances that would lead one to pick up this book are not so different from the circumstances that lead one to sign up for cryonics in the first place. It's a long, hard read without a huge benefit. Accordingly, I wouldn't recommend it.
* [Cryonics: Reaching For Tomorrow](https://www.amazon.com/gp/product/1880209004) - This is a very odd little book presented in a blend of the styles of an academic journal and a popular magazine. I believe it was written in the 90's, and it hasn't aged well. Although the state of the science of preservation hasn't advanced much (the science of recovery is faring better), the cultural mores don't fit well into the current discussion of Cryonics. It's also pretty hard to find. If you stumble upon it, it's worth a perusal, but I wouldn't go out of my way to obtain a copy.

In addition to the long-form journalism I mentioned about specific cryonics cases, there have been several very superficial, yet long, articles about Cryonics. I don't think there's anything here that isn't done better by other references I've listed (especially [Wait, but Why](http://waitbutwhy.com/2016/03/cryonics.html)), but they exist, so there's that.

* [This Buzfeed Article](https://www.buzzfeed.com/joshdean/are-we-warming-up-to-cryonics)
* [What a Time to Be Alive - Forever](http://www.thefader.com/2016/06/23/living-forever-cryonics)

# References I haven't gotten to yet

* Engines of Creation by K. Eric Drexler
* Nanomedicine Volume I: Basic Capabilities by Robert A. Freitas
* Nanomedicine Volume IIA: Biocompatibility by Robert A. Freitas
* The Prospect of Immortality by Robert Ettinger
* The Scientific Conquest of Death - Essays on Infinite Lifespans, edited by the Immortality Institute
* Forever for All by R. Michael Perry
* We Froze the First Man!
* Freezing People Ain't Easy
* Preserving Minds, Saving Lives, edited by Alcor

## Bonus: Fiction

For an extensive listing, consult the TVTropes Article, [Human Popcicles](http://tvtropes.org/pmwiki/pmwiki.php/Main/HumanPopsicle#Examples)

* The First Immortal by James Halperin
* Formerly Brandewyne by Jude Liebermann
