---
title: "Mere Heroes"
---

```{r, results='asis'}
source("../helpers/infobox.R")
meta <- list(
  "Last Revision" = file.info("MereHeroes.Rmd")$mtime
)
infobox(meta, tags$tr(tags$td(tags$b("Note:"), tags$span("Note: This is a personal re-writing of an essay originally penned by Eliezer Yudkowsky on LessWrong. As such, much of the text is exactly Yudkowsky's. Since I'm presenting his ideas, I've decided to preserve his words as well. Never-the-less, I have changed it, extensively in some ways. I don't know how to reconcile my ownership of this version of the text with the original, other to admit outright that I am explicitly committing plagiarism. If Yudkowsky himself objects, I will happily remove this essay at his request."), colspan=2)))
```

As Christians tell the story, Jesus Christ could [walk on water](https://www.biblegateway.com/passage/?search=Matthew+14%3A22-33&version=NRSV), [calm storms](https://www.biblegateway.com/passage/?search=Mark+4%3A35-41&version=NIV), and [exorcise demons](https://www.biblegateway.com/passage/?search=Mark+5%3A1-20&version=NRSV). It must have made for a comfortable life: Followers getting hungry? [Break some bread and pass it around](https://www.biblegateway.com/passage/?search=Matthew+14%3A13-21&version=NRSV). Don't like a tree? [Curse it](https://www.biblegateway.com/passage/?search=Mark+11%3A12-14%2C19-25&version=NRSV). This charmed life ended, however, when [Jesus accepted his arrest](https://www.biblegateway.com/passage/?search=John+18%3A3-14&version=NRSV) and [subsequent crucifixion](https://www.biblegateway.com/passage/?search=Luke+23%3A33-46&version=NRSV). Being nailed to a cross is [not a comfortable way to die](https://en.wikipedia.org/wiki/Crucifixion#Details). But as Christians tell the story, Jesus did this [_knowing_ he would come back to life three days later](https://www.biblegateway.com/passage/?search=Luke+18%3A31-33&version=NRSV), and [then go to Heaven](https://www.biblegateway.com/passage/?search=John+20%3A17&version=NRSV).

What if Jesus of Nazareth never walked on water, and defied the Judean Temple established by the powers of Rome, _in spite of his humanity_? Why would that deserve less honor than that which Christians confer to Jesus Christ? As Sam Harris put it in [The End of Faith](http://smile.amazon.com/End-Faith-Religion-Terror-Future/dp/0393327655/ref=sr_1_1?ie=UTF8&qid=1451509971&sr=8-1&keywords=The+End+of+Faith):

> It is not enough that Jesus was a man who transformed himself to such a degree that the Sermon on the Mount could be his heart's confession. He also had to be the Son of God, born of a virgin, and destined to return to earth trailing clouds of glory. The effect of such dogma is to place the example of Jesus forever out of reach. His teaching ceases to become a set of empirical claims about the linkage between ethics and spiritual insight and instead becomes a gratuitous, and rather gruesome, fairy tale. According to the dogma of Christianity, becoming just like Jesus is impossible.

For contrast, let's consider a mere hero. [John Perry](http://www.nleomf.org/officers/search/search-results/john-william-perry.html) was a New York City police officer, and also a transhumanist. He had taken leave from his precinct one Tuesday in order to file his retirement papers. He was leaving the force at the young age of 38, after 8 years of service, to [start his own law practice](http://www.nypdangels.com/nypd/perry.htm). But on that Tuesday morning, John Perry got word that a plane had slammed into the World Trade Center. Instead of filing his retirement papers, John Perry donned his uniform one last time and rushed to Ground Zero to help. He was killed when the north tower fell.

John Perry [hoped to be cryonically preserved](http://www.plumsite.com/johnperry.html), and had [made the requisite preparations](http://www.alcor.org/problems.html); he had _genuine_ hope of life everlasting. And John Perry put himself in very real, immediate danger anyway. John Perry _knew_ he was risking his life every day on the job. Not because he expected any divine reward, but because there were other people in danger. His life was worth no more than theirs. I did not know John Perry. I do not know if he saw the world this way. But the fact that a transhumanist can still run selflessly into the lobby of a burning building says more about the human spirit than all the martyrs who ever dreamed of rewards in heaven.

Jesus deserves honor. He probably deserves more honor than Christians would grant him. But Jesus Christ anticipated his soul would survive, and so sacrificed a painful death on a cross and [three days in hell](https://en.wikipedia.org/wiki/Harrowing_of_Hell). John Perry was a transhumanist, and so sacrificed a painful death under a building and an eternity in oblivion. Why do we revere the actions of Jesus Christ, while forgetting the mere heroism of John Perry? Perhaps we judge our heroes by the magnitude of their powers, rather than the magnitude of their sacrifices. And that is a travesty.
