---
title: "Some Thoughts on 9-11"
---

```{r}
source('../helpers/infobox.R')
infobox(list(
  "Accurate As Of" = tags$span(id="todaysDate")
))
```

On September 11th, 2001, 2977 people were [murdered by terrorists](https://en.wikipedia.org/wiki/September_11_attacks). Stop for a moment, and try to feel the size of that number. You are one person. 2977 people is 2977 times the number of people you are. 2977 lives were needlessly cut short. Collectively, those people might have lived another 99,000 years.

Now take a deep breath. The following day, roughly 160,000 more people died. That’s more than 53 times the number of people killed by terrorists on 9-11. Try to make yourself feel the size of THAT number. That’s vastly more people than you will ever meet in your lifetime. It’s more than triple the size of my hometown. Imagine three small towns not too far from where you are right now, wiped off the map.

Every day since 9-11-2001, [approximately 160,000 people have died](https://en.wikipedia.org/wiki/Mortality_rate). There have been <span id="daysSince"></span> days since then, meaning roughly <span id="deathsSince"></span> people have died. That’s more than the [entire population of Europe](https://www.google.com/search?q=Population+of+Europe), snuffed out. Try (and fail) to wrap your head around that number. It’s just too overwhelming. Our brains don’t (and can’t) work that way.

Instead, just think for a moment how different the world might be if we were able to prioritize our spending on things that literally stopped people from dying (like evidence-based public health campaigns and medical research), instead of things that make easy re-election campaigns. Think about all the people who could have been alive right now. It’s much bigger than the people who were killed on 9-11 itself. So, sure, [#NeverForget](https://www.facebook.com/hashtag/neverforget), but don’t forget the rest of humanity in the process.

<script>
$(function(){
  var today = new Date();
  $('#todaysDate').text(today.toISOString().slice(0, 10));
  var daysSince = Math.floor((today.getTime() - 1000180800000)/(1000*60*60*24));
  $('#daysSince').text(daysSince.toLocaleString());
  $('#deathsSince').text((daysSince * 160000).toLocaleString());
});
</script>
