---
title: "Get to it: A Homily"
---

# Before

Before, there was nothing. All was silence and stillness and empty. But 'Empty' implies a place without things. Before, there was no place.

Then, with a cataclysmic noise, there was a place. A place with things in it.

It wasn't good or bad. It was just... stuff. Something. Hydrogen.

The stuff formed clumps. Huge clumps that burned. Stars formed and burned. Merged and collapsed. Novaed and Supernovaed. Spun around each other in simple dances. Inside, they transformed the stuff that made them. Took Hydrogen and forged Helium, Lithium, Beryllium, Boron.

Carbon.

As the universe continued to cool, smaller, cooler clumps of stuff formed. Rocks bumped into each other, accumulated into comets, asteroids, rocky little terrestrial planets, and fluffy gas giants.

And for nine billion years, nothing more happened.

# Then

But then, one day, the most interesting thing in the universe happened. Some atoms somewhere near an unremarkable yellow star accidentally linked up in exactly the right way, and became a replicator.

The replicator wasn't like the stuff it was made out of. Rather, the replicator could do something really special and interesting. It could take the stuff around it, and turn that stuff into other replicators, just like it.

Well, mostly like it. Sometimes, replicators grabbed molecules that were like the ones they were made out of, but not exactly the same. Most of the time, that meant the new replicator wouldn't work. Once in awhile, it meant the new replicator worked **better**.

Things continued like this for a while. Replicators replicated, occasionally stumbling upon a better formulation. This halting, accidental process built protections for the replicators: shells and excess reserves of their raw materials. More replicators, more replications.

Some replicators replicated one way. Some other replicators replicated another. The first way worked well, and those replicators' descendants got bigger, and were bacteria. The second way worked well, and those replicators' descendants stayed small, and were archaea.

Sometimes a bacterium would find an archaeon, and use it for parts to make another bacterium. It was a replicator-eat-replicator world.

And for another five-hundred million years, nothing more happened.

# And Then

But then, one day, a bacterium found an archaeon and tried to eat the archaeon to use it for parts. And it didn't work. Instead, the archaeon lived inside the bacterium. The bacterium ate lots of things the archaeon could use to make more archaeon right inside the bacterium. The archaeon, in turn, threw away parts it didn't need, but that the bacterium did. That saved the bacterium all the trouble of making those things itself. It was an unexpected and beautiful relationship.

Together, the bacterium and the archaeon had formed something new. The first complex life.

From this union exploded the life of the world in which we now live.

Everything living thing that we can see with our naked eyes is descended from this life. You and I are both its grandchildren.

# Now

We live in a dangerous, adversarial environment. The brutal truth of our reality is that there is only one inviolate set of laws in the universe: the laws of physics. And they *desperately* want you dead.

We fight against this state of affairs. We clothed ourselves and conquered fire to protect ourselves from the cold of winter. We armed ourselves and built buildings to protect ourselves from the great beasts of the wild. We created language to convey our complex thoughts between each other, and writing to convey those thoughts across time and generations. We invented the methods of science to hasten our climb from victims of physics to gods who bend it to our will.

And even now, we are still likely to lose.

We live in a world replete with dangers we cannot yet best. The Earth below us could explode in a fiery rage of volcanism, spewing chemicals to poison us and ash to hide the sunlight. The sun above us could hurl powerful winds, stripping away our atmosphere as it did to Mars. The rocks beyond it could fall to Earth, smashing our world and destroying us as they did to the Dinosaurs.

But in the two-hundred-thousand years humans have walked the Earth, these things have never happened. Why then should we fear extinction?

We are the masters of this world, but this mastery has come at a cost. We are building incredible new tools. Replicators that conquer our diseases for us. Tiny machines that build the things we want them to. Huge machines that think better and faster than we can.

Any of these projects can turn on us. Some if an evil person masters their technology. Some if we simply fail to understand the dangers they present, and plan our paths accordingly. You see, these new powers sit within the laws of physics. And they *desperately* want you dead.

And so, we are still likely to lose.

# Forever

But what if we don't lose? What does the victory of humanity look like?

Imagining success is integral to achieving it. After all, how can you hope to hit a bullseye if you haven't seen which direction to point?

A generation ago, it was mastery of the stars. We would travel between them as we travel between cities today. And this goal remains noble. But it doesn't answer the question. The most pressing questions of humanity's victory are not the shapes of our expansion but the moralities we enforce within them.

Each day, another hundred and sixty thousand of us die. Conquering the universe achieves nothing of benefit to them. So it is critical that mastery of the universe follows mastery of death.

Each day, millions of animals are tortured and slaughtered for the crime of being desirable food for us. Conquering the universe offers them only the opportunity to suffer on astronomical proportions. So it is critical that mastery of the universe follows mastery of our appetites.

Each day, billions of wild organisms are born into and die in agony. Conquering the universe offers them only the opportunity to suffer on astronomical proportions. So it is critical that mastery of the universe follows mastery of suffering.

But what follows these? What projects shall we persue when our moral obligations are met and we begin to populate the galaxy?

This I do not know. I hope it's [fun](https://www.lesserwrong.com/posts/K4aGvLnHvYgX9pZHS/the-fun-theory-sequence) though. I hope that we  seek horizons, and build great arts, and experience new things. I hope that we play, and learn, and grow to infinity and beyond. I hope that we are free to do these things.

I hope we live long enough to do so. But we are still likely to lose.

There's work to do. Get to it.
