---
title: "Archive"
---

```{r}
library("htmltools")
tags$div(class="panel panel-danger",
  tags$div(class="panel-heading", "Disclaimer"),
  tags$div(class="panel-body", "If you've stumbled upon this page, well done. This is the archive directory. I have placed thing here which no longer represent my beliefs, or I'm otherwise moderately embarassed by. In the interest of intellectual honesty, I feel it's important that they remain in existence. That said, I strongly encourage you *not* to read these; if nothing else, you have better things to do.")
)
```

```{r, message=FALSE}
library("plyr")
library("dplyr")
library("magrittr")
library("DT")
library("stringr")

cbind(
  Name = list.files(".", "*.Rmd"),
  ldply(list.files(".", "*.Rmd", full.names = TRUE), file.info)
) %>%
  filter(! Name %in% c("index.Rmd")) %>%
  arrange(desc(mtime)) %>%
  transmute(
    `Last Modified` = paste0(
        "<a href='https://github.com/aaboyles/Essays/commits/gh-pages/drafts/", Name, "'>",
        substr(mtime, 0, 10), "</a>"
      ),
    Name = paste0(
      "<a href='", str_sub(Name, 1, -5), ".html'>",
      Name %>%
        str_replace_all("([a-z])([A-Z])", "\\1 \\2") %>%
        str_replace_all("([A-Z]+)([A-Z])", "\\1 \\2") %>%
        str_sub(1, -5), "</a>"),
    `Length (bytes)` = size
    ) %>%
  dplyr::select(Name, `Length (bytes)`, `Last Modified`) %>%
  datatable(escape = FALSE)
```
