---
title: "People Who Died in 2017"
---

It felt like [a lot of celebrities died in 2016](http://people.com/celebrity/stars-we-lost-in-2016/) ([see also](https://www.youtube.com/watch?v=PQ6WPo-oW5Q)). But the people who make it onto these sorts of lists tend to be, well, popular. It seems to me that the public completely misses the deaths of people whom they should actually aspire to emulate, rather than celebrities who do things which amuse them. Accordingly, I've collected a short list of people who died in 2017 who did valuable things that most people will never hear about.

As all such lists, this is entirely subjective. [Many noteworthy people die](https://en.wikipedia.org/wiki/Category:2017_deaths) in [any given year](https://en.wikipedia.org/wiki/Category:Deaths_by_year). These are simply people who affected *my* life in some way, and whom I wish more people mourned. Please do no misconstrue a persons' inclusion on this list as an endorsement of any of their specific opinions or behaviors. I put them on the list for the reason that I give *in the list*. I'm not going to write extensive biographies or obituaries, just enough context to convey my reasoning for including them on this list. Accordingly, I won't tell you about the manner of their death unless it's salient to my inclusion of them. If you wish to know more, just follow the links.

One additional note: I've attempted to be diverse in my selections, but in this I've mostly failed. Women are slightly underrepresented. Non-white people are severely underrepresented. Non-academics are severely underrepresented. For the former two, I can only admit my embarrassment at my failure, and resolve to be more inclusive in the future. At the latter, I must defend the bias: more people can and should pursue the horizons of human knowledge.

## Derek Parfit

English Philosopher [Derek Parfit](https://en.wikipedia.org/wiki/Derek_Parfit) died on January 1, 2017. He authored [Reasons and Persons](https://www.amazon.com/Reasons-Persons-Derek-Parfit/dp/019824908X), and the three-volume [On What Matters](https://www.amazon.com/What-Matters-2-Set/dp/0199265925/) [(Volume 3)](https://www.amazon.com/What-Matters-Three-Derek-Parfit/dp/0198778600/).

## Hans Rosling

Swedish Dr. [Hans Rosling](https://en.wikipedia.org/wiki/Hans_Rosling) [died](http://www.gapminder.org/news/sad-to-announce-hans-rosling-passed-away-this-morning/) on February 7, 2017. He presented [a wide variety of TED and TED-like talks](https://www.gapminder.org/videos/) on demographics and global public health.

## Kenneth Arrow

American Economist [Kenneth Arrow](https://en.wikipedia.org/wiki/Kenneth_Arrow) died on February 21, 2017. He shared the 1972 Nobel Prize in Economics, and is well-known for his [eponymous impossibility theorem](https://en.wikipedia.org/wiki/Arrow%27s_impossibility_theorem).

## Stanislav Petrov

Soviet Lieutenant Colonel [Stanislav Petrov](https://en.wikipedia.org/wiki/Stanislav_Petrov) died on May 19, 2017. He [literally saved the world](http://anthony.boyles.cc/drafts/Happy-Petrov-Day.html).

## Maryam Mirzakhani

Iranian Mathematician [Maryam Mirzakhani](https://en.wikipedia.org/wiki/Maryam_Mirzakhani) died on July 14, 2017. She was awarded the 2014 Fields Medal for "her outstanding contributions to the dynamics and geometry of Riemann surfaces and their moduli spaces".

## Anne Dufourmantelle

French philosopher [Anne Dufourmantelle](https://en.wikipedia.org/wiki/Anne_Dufourmantelle) died on July 21, 2017. I must confess that I'd never heard of her before her untimely end, but [she drowned](http://www.bbc.com/news/world-europe-40703606) attempting to save two children who were being carried out to sea. The implications of this should be [obvious to modern utilitarians](https://www.utilitarian.net/singer/by/199704--.htm).

## Vladimir Voevodsky

Russian Professor of Mathematics [Vladimir Voevodsky](https://en.wikipedia.org/wiki/Vladimir_Voevodsky) died on September 30, 2017. He was awarded the 2002 Fields Medal for developing a homotopy theory for algebraic varieties and formulating motivic cohomology.

## Isabella Karle

American Nuclear Chemist [Isabella Karle](https://en.wikipedia.org/wiki/Isabella_Karle) died on October 3, 2017. She worked on the Manhattan Project, where she developed techinques to extract plutonium chloride from mixtures containing plutonium oxide.

## Vera Shlakman

American Economist [Vera Shlakman](https://en.wikipedia.org/wiki/Vera_Shlakman) died on November 5, 2017. She authored an groundbreaking and influential book on female factory workers in 1935. In 1952, She was fired from her position at Queens College following her [invocation of the 5th ammendment](https://www.nytimes.com/2017/11/27/obituaries/vera-shlakman-professor-fired-during-red-scare-dies-at-108.html) in a McCarthyist Senate Internal Subcommittee meeting.

## Jack Doroshow

American Drag Queen Jack Doroshow (a.k.a. [Flawless Sabrina](https://en.wikipedia.org/wiki/Flawless_Sabrina)) died on November 18, 2017. He began [organizing Drag Shows in the late 1950's](https://www.nytimes.com/2017/11/30/obituaries/jack-doroshow-drag-pageant-impresario-dies-at-78.html), long before American society-at-large was actively hostile to anything which eschewed hetero-normativity.

## Jerry Fodor

American Professor of Philosophy [Jerry Fodor](https://en.wikipedia.org/wiki/Jerry_Fodor) died on November 29, 2017. His multidisciplinary work [seeded a variety of fields](https://www.nytimes.com/2017/11/30/obituaries/jerry-a-fodor-dead-philosopher-of-the-mind.html) dealing with intelligence, notably including artificial intelligence and cognitive science.

## Calestous Juma

Kenyan Professor of International Development [Calestous Juma](https://en.wikipedia.org/wiki/Calestous_Juma) died on December 15, 2017. His 1989 book "The Gene Hunters," on the potential for genetic modification to solve agricultural crises, [lead to the](https://www.nytimes.com/2018/01/01/science/calestous-juma-african-agriculture-dies.html?ribbon-ad-idx=10&rref=obituaries) 1992 Convention on Biological Diversity, an international treaty with 150 signatories.

## Jan Arthur

American Musician Jan Arthur died on December 16, 2017. He was Conductor of the Chancel Choir for [All Saints Lutheran Church](https://www.saintsonhigh.org/) in Worthington, Ohio from 1981 until his recent retirement. He was also one of the kindest, gentlest, and most interesting people I've ever known.

## Kenichi Yamamoto

Japanese Engineer Kenichi Yamamoto died on December 20, 2017. He oversaw the team at Mazda that invented a commercially viable version of the [Wankel Engine](https://en.wikipedia.org/wiki/Wankel_engine). He went on to serve as a President and Chair of the Board at Mazda.

## Erica Garner

American Activist [Erica Garner](https://en.wikipedia.org/wiki/Erica_Garner) died on December 30, 2017. Following [her father's homicide](https://en.wikipedia.org/wiki/Death_of_Eric_Garner), Garner [organized regular protests](https://www.nytimes.com/2017/12/30/nyregion/erica-garner-dead.html?ribbon-ad-idx=10&rref=obituaries), inspiring others to rise to the front of the [#BlackLivesMatter](https://twitter.com/search?q=%23BlackLivesMatter&src=tyah) movement.

## Ben Barres

American Neuroscientist [Ben Barres](https://en.wikipedia.org/wiki/Ben_Barres) died on December 27, 2017. He is also known to be [a champion for gender equality in academia](https://faculty.harvard.edu/events/186/some-reflections-dearth-women-and-science-talk-ben-barres-professor-neurobiology-stanford). Barres himself was transgender, transitioning only after earning an MD from Dartmouth, PhD from Harvard, and faculty appointment at Stanford, all as a woman. His research studying the roles of [glial cells in neurodegenerative disorders](http://med.stanford.edu/news/all-news/2017/12/neuroscientist-ben-barres-dies-at-63.html) will likely prove pivotal in devising cures for them.

Roughly 58 million humans died this year. I mourn humanity's loss of each, but especially of these. Spare a moment for them, and wonder what you could do to be mourned as they should be.
